//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace InLine.Service.Data
{
    
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using InLine;
    
    public partial interface IObrazacID1Potvrda2010A
    {
    	IList<Model.Admin.StatusPoruka> Insert(Model.Data.Item.ObrazacID1Potvrda2010AItem item);
        IList<Model.Admin.StatusPoruka> Update(Model.Data.Item.ObrazacID1Potvrda2010AItem item);
        IList<Model.Admin.StatusPoruka> Delete(Model.Data.Item.ObrazacID1Potvrda2010AItem item);
    	IEnumerable<Model.Data.ObrazacID1Potvrda2010A> SelectResult(long? ID_ObrazacID1Potvrda2010A);
    	Model.Data.ObrazacID1Potvrda2010A InsertResult(Model.Data.Item.ObrazacID1Potvrda2010AItem item);
    	Model.Data.ObrazacID1Potvrda2010A UpdateResult(Model.Data.Item.ObrazacID1Potvrda2010AItem item);
    	int DeleteResult(Model.Data.Item.ObrazacID1Potvrda2010AItem item);
    	
        Model.Data.ObrazacID1Potvrda2010A FindID(long id);
        //IEnumerable<Model.Data.ObrazacID1Potvrda2010A> GetGridData(string filter, string sort, long? start, long? count, bool customserach = false);
    	IEnumerable<Model.Data.ObrazacID1Potvrda2010A> GetGridData(string filter, string key, string value, string sort, long? start, long? count, bool customserach = false);
        long GetCount(string filter, string key, string value, bool customserach = false);
    	IEnumerable<Model.Data.ObrazacID1Potvrda2010A> GetData(List<Model.Data.Field.ObrazacID1Potvrda2010A> fields, List<Model.Data.Filter.ObrazacID1Potvrda2010A>  filter, List<Model.Data.Sort.ObrazacID1Potvrda2010A>  sort, long? start = null, long? count = null);
    }
}
