//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace InLine.Service.Data
{
    
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using InLine;
    
    public partial interface IObrazacPDVK
    {
    	IList<Model.Admin.StatusPoruka> Insert(Model.Data.Item.ObrazacPDVKItem item);
        IList<Model.Admin.StatusPoruka> Update(Model.Data.Item.ObrazacPDVKItem item);
        IList<Model.Admin.StatusPoruka> Delete(Model.Data.Item.ObrazacPDVKItem item);
    	IEnumerable<Model.Data.ObrazacPDVK> SelectResult(long? ID_ObrazacPDVK);
    	Model.Data.ObrazacPDVK InsertResult(Model.Data.Item.ObrazacPDVKItem item);
    	Model.Data.ObrazacPDVK UpdateResult(Model.Data.Item.ObrazacPDVKItem item);
    	int DeleteResult(Model.Data.Item.ObrazacPDVKItem item);
    	
        Model.Data.ObrazacPDVK FindID(long id);
        //IEnumerable<Model.Data.ObrazacPDVK> GetGridData(string filter, string sort, long? start, long? count, bool customserach = false);
    	IEnumerable<Model.Data.ObrazacPDVK> GetGridData(string filter, string key, string value, string sort, long? start, long? count, bool customserach = false);
        long GetCount(string filter, string key, string value, bool customserach = false);
    	IEnumerable<Model.Data.ObrazacPDVK> GetData(List<Model.Data.Field.ObrazacPDVK> fields, List<Model.Data.Filter.ObrazacPDVK>  filter, List<Model.Data.Sort.ObrazacPDVK>  sort, long? start = null, long? count = null);
    }
}
