//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace InLine.Service.Data
{
    
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using InLine;
    
    public partial interface IOdbitak
    {
    	IList<Model.Admin.StatusPoruka> Insert(Model.Data.Item.OdbitakItem item);
        IList<Model.Admin.StatusPoruka> Update(Model.Data.Item.OdbitakItem item);
        IList<Model.Admin.StatusPoruka> Delete(Model.Data.Item.OdbitakItem item);
    	IEnumerable<Model.Data.Odbitak> SelectResult(long? ID_Odbitak);
    	Model.Data.Odbitak InsertResult(Model.Data.Item.OdbitakItem item);
    	Model.Data.Odbitak UpdateResult(Model.Data.Item.OdbitakItem item);
    	int DeleteResult(Model.Data.Item.OdbitakItem item);
    	
        Model.Data.Odbitak FindID(long id);
        //IEnumerable<Model.Data.Odbitak> GetGridData(string filter, string sort, long? start, long? count, bool customserach = false);
    	IEnumerable<Model.Data.Odbitak> GetGridData(string filter, string key, string value, string sort, long? start, long? count, bool customserach = false);
        long GetCount(string filter, string key, string value, bool customserach = false);
    	IEnumerable<Model.Data.Odbitak> GetData(List<Model.Data.Field.Odbitak> fields, List<Model.Data.Filter.Odbitak>  filter, List<Model.Data.Sort.Odbitak>  sort, long? start = null, long? count = null);
    }
}
