//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Field
{
    public enum DatotekaPolje
    {
    	ID_DatotekaPolje,
    	ID_Datoteka,
    	ID_DatotekaVrPolje,
    	ValueBit,
    	ValueString,
    	ValueInt,
    	ValueMoney,
    	ValueDate,
    	ValueTime,
    	ValueDateTime,
    	ValueDecimal,
    	Zapis,
    }
}
