//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.FieldString
{
    public static class DatotekaIzvod2012A
    {
    		public const string DatotekaIzvod2012AEntity = "DatotekaIzvod2012A";
    
    		public const string ID_DatotekaIzvod2012A = "ID_DatotekaIzvod2012A";
    		public const string ID_DatotekaIzvod = "ID_DatotekaIzvod";
    		public const string VBDI = "VBDI";
    		public const string Naziv = "Naziv";
    		public const string OIB = "OIB";
    		public const string Vrsta = "Vrsta";
    		public const string Datum = "Datum";
    }
}
