//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.FieldString
{
    public static class DatotekaIzvod
    {
    		public const string DatotekaIzvodEntity = "DatotekaIzvod";
    
    		public const string ID_DatotekaIzvod = "ID_DatotekaIzvod";
    		public const string ID_Zapis = "ID_Zapis";
    		public const string ID_IzvodPosiljatelj = "ID_IzvodPosiljatelj";
    		public const string Datum = "Datum";
    		public const string RedniBroj = "RedniBroj";
    		public const string IDDatotekaIzvodVerzija = "IDDatotekaIzvodVerzija";
    		public const string DatotekaNaziv = "DatotekaNaziv";
    		public const string Datoteka = "Datoteka";
    }
}
