//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Field
{
    public enum DohodakPrimateljPrimitak
    {
    	ID_DohodakPrimateljPrimitak,
    	ID_DohodakPrimatelj,
    	ID_Primitak,
    	IznosBruto,
    	IznosDohodak,
    	IznosNeto,
    	IznosTrosak,
    }
}
