//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.FieldString
{
    public static class HUBKontrola
    {
    		public const string HUBKontrolaEntity = "HUBKontrola";
    
    		public const string IDHUBKontrola = "IDHUBKontrola";
    		public const string Oznaka = "Oznaka";
    		public const string Naziv = "Naziv";
    		public const string NazivKr = "NazivKr";
    		public const string Koristi = "Koristi";
    }
}
