//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Item
{
    using System;
    using System.Collections.Generic;
    
    public partial class KalendarKvartalItem 
    {
    
    	public KalendarKvartalItem() {}
    	public KalendarKvartalItem(int? kvartal)
    	{
    		Kvartal = kvartal;
    	}
    
        public int? Kvartal { get; set; }
        public string Oznaka { get; set; }
        public string Naziv { get; set; }
    
    	public KalendarKvartalItem(Model.Data.KalendarKvartal item)
    	{
    	    this.Kvartal = item.Kvartal;
        this.Oznaka = item.Oznaka;
        this.Naziv = item.Naziv;
    	}
    
    	public KalendarKvartalItem(dynamic item)
    	{
    	    this.Kvartal = item.Kvartal;
        this.Oznaka = item.Oznaka;
        this.Naziv = item.Naziv;
    	}
    }
}
