//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KontniPlanTemeljnicaVr
    {
    
        public long ID
    	{
    		get { return this.ID_KontniPlanTemeljnicaVr; }
    		set { this.ID_KontniPlanTemeljnicaVr = value; }
    	}
        public long ID_KontniPlanTemeljnicaVr { get; set; }
        public long ID_KontniPlan { get; set; }
        public int IDTemeljnicaVrVr { get; set; }
        public long ID_TemeljnicaVr { get; set; }
    
        public virtual KontniPlan KontniPlan { get; set; }
        public virtual TemeljnicaVr TemeljnicaVr { get; set; }
        public virtual TemeljnicaVrVr TemeljnicaVrVr { get; set; }
    }
}
