//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Field
{
    public enum MjestoPosta
    {
    	ID_MjestoPosta,
    	ID_Mjesto,
    	ID_Posta,
    	DioMjesta,
    	StsMjestoPosta,
    	IzborMjestoPosta,
    	PBrStari,
    	Oznaka,
    	Naziv,
    	NazivAlt,
    	NazivHPT,
    	NazivKr,
    	Kratica,
    	Opis,
    	OpisHPT,
    	AdresaBezMjesta,
    }
}
