//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Item
{
    using System;
    using System.Collections.Generic;
    
    public partial class NarodnostItem 
    {
    
    	public NarodnostItem() {}
    	public NarodnostItem(long? id_Narodnost)
    	{
    		ID_Narodnost = id_Narodnost;
    	}
    
        public long? ID
    	{
    		get { return this.ID_Narodnost; }
    		set { this.ID_Narodnost = value; }
    	}
        public long? ID_Narodnost { get; set; }
        public string Oznaka { get; set; }
        public string Naziv { get; set; }
        public string NazivKr { get; set; }
        public string Kratica { get; set; }
    
    	public NarodnostItem(Model.Data.Narodnost item)
    	{
    	    this.ID_Narodnost = item.ID_Narodnost;
        this.Oznaka = item.Oznaka;
        this.Naziv = item.Naziv;
        this.NazivKr = item.NazivKr;
        this.Kratica = item.Kratica;
    	}
    
    	public NarodnostItem(dynamic item)
    	{
    	    this.ID_Narodnost = item.ID_Narodnost;
        this.Oznaka = item.Oznaka;
        this.Naziv = item.Naziv;
        this.NazivKr = item.NazivKr;
        this.Kratica = item.Kratica;
    	}
    }
}
