//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Item
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObrazacRSmStaz2005AItem 
    {
    
    	public ObrazacRSmStaz2005AItem() {}
    	public ObrazacRSmStaz2005AItem(int? idObrazacRSmStaz2005A)
    	{
    		IDObrazacRSmStaz2005A = idObrazacRSmStaz2005A;
    	}
    
        public int? IDObrazacRSmStaz2005A { get; set; }
        public string Oznaka { get; set; }
        public string Naziv { get; set; }
        public string NazivKr { get; set; }
        public string Kratica { get; set; }
    
    	public ObrazacRSmStaz2005AItem(Model.Data.ObrazacRSmStaz2005A item)
    	{
    	    this.IDObrazacRSmStaz2005A = item.IDObrazacRSmStaz2005A;
        this.Oznaka = item.Oznaka;
        this.Naziv = item.Naziv;
        this.NazivKr = item.NazivKr;
        this.Kratica = item.Kratica;
    	}
    
    	public ObrazacRSmStaz2005AItem(dynamic item)
    	{
    	    this.IDObrazacRSmStaz2005A = item.IDObrazacRSmStaz2005A;
        this.Oznaka = item.Oznaka;
        this.Naziv = item.Naziv;
        this.NazivKr = item.NazivKr;
        this.Kratica = item.Kratica;
    	}
    }
}
