//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.FieldString
{
    public static class ObrazacPDV
    {
    		public const string ObrazacPDVEntity = "ObrazacPDV";
    
    		public const string ID_ObrazacPDV = "ID_ObrazacPDV";
    		public const string ID_Zapis = "ID_Zapis";
    		public const string ID_PoslovnaGodina = "ID_PoslovnaGodina";
    		public const string Period = "Period";
    }
}
