//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpcinaGr
    {
    
        public OpcinaGr()
        {
    
            this.OpcinaGrOpcina = new HashSet<OpcinaGrOpcina>();
        }
    
        public long ID
    	{
    		get { return this.ID_OpcinaGr; }
    		set { this.ID_OpcinaGr = value; }
    	}
        public long ID_OpcinaGr { get; set; }
        public string Oznaka { get; set; }
        public string Naziv { get; set; }
        public string NazivKr { get; set; }
        public string Kratica { get; set; }
        public string Opis { get; set; }
        public long? ID_OpcinaGrTip { get; set; }
    
        public virtual OpcinaGrTip OpcinaGrTip { get; set; }
        public virtual ICollection<OpcinaGrOpcina> OpcinaGrOpcina { get; set; }
    }
}
