//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Item
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpcinaGrItem 
    {
    
    	public OpcinaGrItem() {}
    	public OpcinaGrItem(long? id_OpcinaGr)
    	{
    		ID_OpcinaGr = id_OpcinaGr;
    	}
    
        public long? ID
    	{
    		get { return this.ID_OpcinaGr; }
    		set { this.ID_OpcinaGr = value; }
    	}
        public long? ID_OpcinaGr { get; set; }
        public string Oznaka { get; set; }
        public string Naziv { get; set; }
        public string NazivKr { get; set; }
        public string Kratica { get; set; }
        public string Opis { get; set; }
        public long? ID_OpcinaGrTip { get; set; }
    
    	public OpcinaGrItem(Model.Data.OpcinaGr item)
    	{
    	    this.ID_OpcinaGr = item.ID_OpcinaGr;
        this.Oznaka = item.Oznaka;
        this.Naziv = item.Naziv;
        this.NazivKr = item.NazivKr;
        this.Kratica = item.Kratica;
        this.Opis = item.Opis;
        this.ID_OpcinaGrTip = item.ID_OpcinaGrTip;
    	}
    
    	public OpcinaGrItem(dynamic item)
    	{
    	    this.ID_OpcinaGr = item.ID_OpcinaGr;
        this.Oznaka = item.Oznaka;
        this.Naziv = item.Naziv;
        this.NazivKr = item.NazivKr;
        this.Kratica = item.Kratica;
        this.Opis = item.Opis;
        this.ID_OpcinaGrTip = item.ID_OpcinaGrTip;
    	}
    }
}
