//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Field
{
    public enum PoslovnaGodinaSubjekt
    {
    	ID_PoslovnaGodinaSubjekt,
    	ID_PoslovnaGodina,
    	ID_Subjekt,
    }
}
