//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoslovnaGodina
    {
    
        public PoslovnaGodina()
        {
    
            this.KontniPlan = new HashSet<KontniPlan>();
            this.KnjigaIRA = new HashSet<KnjigaIRA>();
            this.KnjigaURA = new HashSet<KnjigaURA>();
            this.ObrazacPDV = new HashSet<ObrazacPDV>();
            this.ObrazacPDVK = new HashSet<ObrazacPDVK>();
            this.PoslovnaGodinaSubjekt = new HashSet<PoslovnaGodinaSubjekt>();
        }
    
        public long ID
    	{
    		get { return this.ID_PoslovnaGodina; }
    		set { this.ID_PoslovnaGodina = value; }
    	}
        public long ID_PoslovnaGodina { get; set; }
        public long ID_PoslovniSubjekt { get; set; }
        public int Godina { get; set; }
        public DateTime DatumOd { get; set; }
        public DateTime DatumDo { get; set; }
        public string IDValuta { get; set; }
    
        public virtual ICollection<KontniPlan> KontniPlan { get; set; }
        public virtual ICollection<KnjigaIRA> KnjigaIRA { get; set; }
        public virtual ICollection<KnjigaURA> KnjigaURA { get; set; }
        public virtual ICollection<ObrazacPDV> ObrazacPDV { get; set; }
        public virtual ICollection<ObrazacPDVK> ObrazacPDVK { get; set; }
        public virtual PoslovniSubjekt PoslovniSubjekt { get; set; }
        public virtual Valuta Valuta { get; set; }
        public virtual ICollection<PoslovnaGodinaSubjekt> PoslovnaGodinaSubjekt { get; set; }
    }
}
