//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.FieldString
{
    public static class RacunUlazKontniPlan
    {
    		public const string RacunUlazKontniPlanEntity = "RacunUlazKontniPlan";
    
    		public const string ID_RacunUlazKontniPlan = "ID_RacunUlazKontniPlan";
    		public const string ID_RacunUlaz = "ID_RacunUlaz";
    		public const string ID_KontniPlan = "ID_KontniPlan";
    		public const string ID_Shema = "ID_Shema";
    		public const string ID_KontniPlanAnalitika = "ID_KontniPlanAnalitika";
    }
}
