//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShemaGrShema
    {
    
        public long ID
    	{
    		get { return this.ID_ShemaGrShema; }
    		set { this.ID_ShemaGrShema = value; }
    	}
        public long ID_ShemaGrShema { get; set; }
        public long ID_ShemaGr { get; set; }
        public long ID_Shema { get; set; }
    
        public virtual Shema Shema { get; set; }
        public virtual ShemaGr ShemaGr { get; set; }
    }
}
