//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.FieldString
{
    public static class TablicaPoljeUI
    {
    		public const string TablicaPoljeUIEntity = "TablicaPoljeUI";
    
    		public const string TablicaShema = "TablicaShema";
    		public const string TablicaNaziv = "TablicaNaziv";
    		public const string TablicaPoljeNaziv = "TablicaPoljeNaziv";
    		public const string Labela = "Labela";
    		public const string Opis = "Opis";
    }
}
