//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.FieldString
{
    public static class TecajListaSt
    {
    		public const string TecajListaStEntity = "TecajListaSt";
    
    		public const string ID_TecajListaSt = "ID_TecajListaSt";
    		public const string ID_TecajLista = "ID_TecajLista";
    		public const string IDDrzavaIz = "IDDrzavaIz";
    		public const string IDDrzavaU = "IDDrzavaU";
    		public const string IDValutaIz = "IDValutaIz";
    		public const string IDValutaU = "IDValutaU";
    		public const string BrojJedinica = "BrojJedinica";
    }
}
