//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.FieldString
{
    public static class UgovorStanOtkupKupac
    {
    		public const string UgovorStanOtkupKupacEntity = "UgovorStanOtkupKupac";
    
    		public const string ID_UgovorStanOtkupKupac = "ID_UgovorStanOtkupKupac";
    		public const string ID_UgovorStanOtkup = "ID_UgovorStanOtkup";
    		public const string ID_Kupac = "ID_Kupac";
    		public const string Nositelj = "Nositelj";
    }
}
