//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.FieldString.View
{
    public static class PoslovnaGodinaDetalj
    {
    		public const string PoslovnaGodinaDetaljEntity = "PoslovnaGodinaDetalj";
    
    		public const string ID_PoslovnaGodina = "ID_PoslovnaGodina";
    		public const string ID_PoslovniSubjekt = "ID_PoslovniSubjekt";
    		public const string Godina = "Godina";
    		public const string DatumOd = "DatumOd";
    		public const string DatumDo = "DatumDo";
    		public const string IDValuta = "IDValuta";
    }
}
