//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Item.View
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemeljnicaStItem 
    {
    
    	public TemeljnicaStItem() {}
    	public TemeljnicaStItem(long? id_TemeljnicaSt, long? id_Temeljnica, int? redniBroj, string kontniPlanStNaziv, DateTime? datum, decimal? iznosDuguje, decimal? iznosPotrazuje, string idValuta, decimal? iznosDugujeValuta, decimal? iznosPotrazujeValuta, decimal? tecaj, long? id_KontniPlanSt, string konto)
    	{
    		ID_TemeljnicaSt = id_TemeljnicaSt;
    		ID_Temeljnica = id_Temeljnica;
    		RedniBroj = redniBroj;
    		KontniPlanStNaziv = kontniPlanStNaziv;
    		Datum = datum;
    		IznosDuguje = iznosDuguje;
    		IznosPotrazuje = iznosPotrazuje;
    		IDValuta = idValuta;
    		IznosDugujeValuta = iznosDugujeValuta;
    		IznosPotrazujeValuta = iznosPotrazujeValuta;
    		Tecaj = tecaj;
    		ID_KontniPlanSt = id_KontniPlanSt;
    		Konto = konto;
    	}
    
        public long? ID_TemeljnicaSt { get; set; }
        public long? ID_Temeljnica { get; set; }
        public int? RedniBroj { get; set; }
        public string KontniPlanStNaziv { get; set; }
        public DateTime? Datum { get; set; }
        public decimal? IznosDuguje { get; set; }
        public decimal? IznosPotrazuje { get; set; }
        public string IDValuta { get; set; }
        public decimal? IznosDugujeValuta { get; set; }
        public decimal? IznosPotrazujeValuta { get; set; }
        public decimal? Tecaj { get; set; }
        public long? ID_KontniPlanSt { get; set; }
        public string Konto { get; set; }
    
    	public TemeljnicaStItem(Model.Data.View.TemeljnicaSt item)
    	{
    	    this.ID_TemeljnicaSt = item.ID_TemeljnicaSt;
        this.ID_Temeljnica = item.ID_Temeljnica;
        this.RedniBroj = item.RedniBroj;
        this.KontniPlanStNaziv = item.KontniPlanStNaziv;
        this.Datum = item.Datum;
        this.IznosDuguje = item.IznosDuguje;
        this.IznosPotrazuje = item.IznosPotrazuje;
        this.IDValuta = item.IDValuta;
        this.IznosDugujeValuta = item.IznosDugujeValuta;
        this.IznosPotrazujeValuta = item.IznosPotrazujeValuta;
        this.Tecaj = item.Tecaj;
        this.ID_KontniPlanSt = item.ID_KontniPlanSt;
        this.Konto = item.Konto;
    	}
    
    	public TemeljnicaStItem(dynamic item)
    	{
    	    this.ID_TemeljnicaSt = item.ID_TemeljnicaSt;
        this.ID_Temeljnica = item.ID_Temeljnica;
        this.RedniBroj = item.RedniBroj;
        this.KontniPlanStNaziv = item.KontniPlanStNaziv;
        this.Datum = item.Datum;
        this.IznosDuguje = item.IznosDuguje;
        this.IznosPotrazuje = item.IznosPotrazuje;
        this.IDValuta = item.IDValuta;
        this.IznosDugujeValuta = item.IznosDugujeValuta;
        this.IznosPotrazujeValuta = item.IznosPotrazujeValuta;
        this.Tecaj = item.Tecaj;
        this.ID_KontniPlanSt = item.ID_KontniPlanSt;
        this.Konto = item.Konto;
    	}
    }
}
