//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data.Item
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZaposlenjeItem 
    {
    
    	public ZaposlenjeItem() {}
    	public ZaposlenjeItem(long? id_Zaposlenje)
    	{
    		ID_Zaposlenje = id_Zaposlenje;
    	}
    
        public long? ID
    	{
    		get { return this.ID_Zaposlenje; }
    		set { this.ID_Zaposlenje = value; }
    	}
        public long? ID_Zaposlenje { get; set; }
        public long? ID_Osoba { get; set; }
        public long? ID_Subjekt { get; set; }
        public DateTime? DatumOd { get; set; }
        public DateTime? DatumDo { get; set; }
        public int? StazGodina { get; set; }
        public int? StazMjesec { get; set; }
        public int? StazDan { get; set; }
        public int? IDMirovinskiStup { get; set; }
        public bool? PrvoZaposlenje { get; set; }
    
    	public ZaposlenjeItem(Model.Data.Zaposlenje item)
    	{
    	    this.ID_Zaposlenje = item.ID_Zaposlenje;
        this.ID_Osoba = item.ID_Osoba;
        this.ID_Subjekt = item.ID_Subjekt;
        this.DatumOd = item.DatumOd;
        this.DatumDo = item.DatumDo;
        this.StazGodina = item.StazGodina;
        this.StazMjesec = item.StazMjesec;
        this.StazDan = item.StazDan;
        this.IDMirovinskiStup = item.IDMirovinskiStup;
        this.PrvoZaposlenje = item.PrvoZaposlenje;
    	}
    
    	public ZaposlenjeItem(dynamic item)
    	{
    	    this.ID_Zaposlenje = item.ID_Zaposlenje;
        this.ID_Osoba = item.ID_Osoba;
        this.ID_Subjekt = item.ID_Subjekt;
        this.DatumOd = item.DatumOd;
        this.DatumDo = item.DatumDo;
        this.StazGodina = item.StazGodina;
        this.StazMjesec = item.StazMjesec;
        this.StazDan = item.StazDan;
        this.IDMirovinskiStup = item.IDMirovinskiStup;
        this.PrvoZaposlenje = item.PrvoZaposlenje;
    	}
    }
}
