//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZupanijaGr
    {
    
        public ZupanijaGr()
        {
    
            this.ZupanijaGrZupanija = new HashSet<ZupanijaGrZupanija>();
        }
    
        public long ID
    	{
    		get { return this.ID_ZupanijaGr; }
    		set { this.ID_ZupanijaGr = value; }
    	}
        public long ID_ZupanijaGr { get; set; }
        public string Oznaka { get; set; }
        public string Naziv { get; set; }
        public string NazivKr { get; set; }
        public string Kratica { get; set; }
        public string Opis { get; set; }
        public long? ID_ZupanijaGrTip { get; set; }
    
        public virtual ZupanijaGrTip ZupanijaGrTip { get; set; }
        public virtual ICollection<ZupanijaGrZupanija> ZupanijaGrZupanija { get; set; }
    }
}
