//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormaStGrX
    {
        public FormaStGrX()
        {
            this.FormaStGrXFormaSt = new HashSet<FormaStGrXFormaSt>();
            this.FormaStGrXFormaStGrX = new HashSet<FormaStGrXFormaStGrX>();
            this.FormaStGrXFormaStGrX1 = new HashSet<FormaStGrXFormaStGrX>();
            this.KorisnikGrXFormaStGrX = new HashSet<KorisnikGrXFormaStGrX>();
        }
    
        public long ID
    	{
    		get { return this.ID_FormaStGrX; }
    		set { this.ID_FormaStGrX = value; }
    	}
        public long ID_FormaStGrX { get; set; }
        public string Oznaka { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Napomena { get; set; }
    
        public virtual ICollection<FormaStGrXFormaSt> FormaStGrXFormaSt { get; set; }
        public virtual ICollection<FormaStGrXFormaStGrX> FormaStGrXFormaStGrX { get; set; }
        public virtual ICollection<FormaStGrXFormaStGrX> FormaStGrXFormaStGrX1 { get; set; }
        public virtual ICollection<KorisnikGrXFormaStGrX> KorisnikGrXFormaStGrX { get; set; }
    }
}
