//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportStGrXReportSt
    {
        public ReportStGrXReportSt()
        {
            this.ReportStGrXReportSt1 = new HashSet<ReportStGrXReportSt>();
        }
    
        public long ID
    	{
    		get { return this.ID_ReportStGrXReportSt; }
    		set { this.ID_ReportStGrXReportSt = value; }
    	}
        public long ID_ReportStGrXReportSt { get; set; }
        public long ID_ReportStGrX { get; set; }
        public int IDReport { get; set; }
        public int IDReportSt { get; set; }
        public long? ID_ReportStGrXReportStNad { get; set; }
    
        public virtual ReportStGrX ReportStGrX { get; set; }
        public virtual ReportSt ReportSt { get; set; }
        public virtual ICollection<ReportStGrXReportSt> ReportStGrXReportSt1 { get; set; }
        public virtual ReportStGrXReportSt ReportStGrXReportSt2 { get; set; }
    }
}
