//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.ReportGrReport = new HashSet<ReportGrReport>();
            this.ReportGrXReport = new HashSet<ReportGrXReport>();
            this.ReportSt = new HashSet<ReportSt>();
            this.ReportVr = new HashSet<ReportVr>();
        }
    
        public int IDReport { get; set; }
        public string Oznaka { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Napomena { get; set; }
    
        public virtual ICollection<ReportGrReport> ReportGrReport { get; set; }
        public virtual ICollection<ReportGrXReport> ReportGrXReport { get; set; }
        public virtual ICollection<ReportSt> ReportSt { get; set; }
        public virtual ICollection<ReportVr> ReportVr { get; set; }
    }
}
