//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.Model.Admin
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablicaPoljeGrTablicaPolje
    {
        public TablicaPoljeGrTablicaPolje()
        {
            this.TablicaPoljeGrTablicaPolje1 = new HashSet<TablicaPoljeGrTablicaPolje>();
        }
    
        public long ID
    	{
    		get { return this.ID_TablicaPoljeGrTablicaPolje; }
    		set { this.ID_TablicaPoljeGrTablicaPolje = value; }
    	}
        public long ID_TablicaPoljeGrTablicaPolje { get; set; }
        public long ID_TablicaPoljeGr { get; set; }
        public bool TablicaKorisnik { get; set; }
        public string TablicaShema { get; set; }
        public string TablicaNaziv { get; set; }
        public string TablicaPoljeNaziv { get; set; }
        public long? ID_TablicaPoljeGrTablicaPoljeNad { get; set; }
    
        public virtual TablicaPoljeGr TablicaPoljeGr { get; set; }
        public virtual TablicaPolje TablicaPolje { get; set; }
        public virtual ICollection<TablicaPoljeGrTablicaPolje> TablicaPoljeGrTablicaPolje1 { get; set; }
        public virtual TablicaPoljeGrTablicaPolje TablicaPoljeGrTablicaPolje2 { get; set; }
    }
}
