//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InLine.Repository.Data.CRUD
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Diagnostics;
    using System.Data.Objects;
    using InLine;
    
    public partial class Dohodak
    {
    	#region Fields
        
    	public Model.Data.Context _context;
        
    	#endregion
    
    
    
        #region Constructors
        
    	public Dohodak(string connstring)
        {
            _context = new Model.Data.Context(connstring);
        }
        
    	#endregion
    
    
    	#region Methods
       		
    			public void Delete(Model.Data.Item.DohodakItem item)
    			{
    				_context.USP_Dohodak_DELETE(item.ID_Dohodak);
    			}
    
    				
    			public ObjectResult<int?> DeleteResult(Model.Data.Item.DohodakItem item)
    			{
    				return _context.USP_Dohodak_DELETE(item.ID_Dohodak);
    			}	
    									
    			public void Insert(Model.Data.Item.DohodakItem item)
    			{
    				_context.USP_Dohodak_INSERT(item.ID_DohodakIsplatitelj, item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Godina, item.Mjesec, item.DatumOd, item.DatumDo, item.DatumIsplata, item.DatumPodnosenje, item.DatumUplataDoprinos, item.DatumUplataPorez, item.ID_PrimateljKoeficijentGr, item.IDObrazacRSmObracunVr2005A, item.IDObrazacRSmObveznikVr2005A);
    			}
    
    			public ObjectResult<Model.Data.Dohodak> InsertResult(Model.Data.Item.DohodakItem item)
    			{
    				return _context.USP_Dohodak_INSERT(item.ID_DohodakIsplatitelj, item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Godina, item.Mjesec, item.DatumOd, item.DatumDo, item.DatumIsplata, item.DatumPodnosenje, item.DatumUplataDoprinos, item.DatumUplataPorez, item.ID_PrimateljKoeficijentGr, item.IDObrazacRSmObracunVr2005A, item.IDObrazacRSmObveznikVr2005A);
    			}	
    									
    				
    			public void Select(Nullable<long> ID_Dohodak)
    			{
    				_context.USP_Dohodak_SELECT(ID_Dohodak);
    			}
    
    					
    			public ObjectResult<Model.Data.Dohodak> SelectResult(Nullable<long> ID_Dohodak)
            	{
                	return _context.USP_Dohodak_SELECT(ID_Dohodak);
            	}			
    				
    			public void Update(Model.Data.Item.DohodakItem item)
    			{
    				_context.USP_Dohodak_UPDATE(item.ID_Dohodak, item.ID_DohodakIsplatitelj, item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Godina, item.Mjesec, item.DatumOd, item.DatumDo, item.DatumIsplata, item.DatumPodnosenje, item.DatumUplataDoprinos, item.DatumUplataPorez, item.ID_PrimateljKoeficijentGr, item.IDObrazacRSmObracunVr2005A, item.IDObrazacRSmObveznikVr2005A);
    			}
    
    					
    			public ObjectResult<Model.Data.Dohodak> UpdateResult(Model.Data.Item.DohodakItem item)
    			{
    				return _context.USP_Dohodak_UPDATE(item.ID_Dohodak, item.ID_DohodakIsplatitelj, item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Godina, item.Mjesec, item.DatumOd, item.DatumDo, item.DatumIsplata, item.DatumPodnosenje, item.DatumUplataDoprinos, item.DatumUplataPorez, item.ID_PrimateljKoeficijentGr, item.IDObrazacRSmObracunVr2005A, item.IDObrazacRSmObveznikVr2005A);
    			}
    										
    		
    #endregion
    	
    }
    
}
