//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InLine.Repository.Data.CRUD
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Diagnostics;
    using System.Data.Objects;
    using InLine;
    
    public partial class Drzava
    {
    	#region Fields
        
    	public Model.Data.Context _context;
        
    	#endregion
    
    
    
        #region Constructors
        
    	public Drzava(string connstring)
        {
            _context = new Model.Data.Context(connstring);
        }
        
    	#endregion
    
    
    	#region Methods
       		
    			public void Delete(Model.Data.Item.DrzavaItem item)
    			{
    				_context.USP_Drzava_DELETE(item.IDDrzava);
    			}
    
    				
    			public ObjectResult<int?> DeleteResult(Model.Data.Item.DrzavaItem item)
    			{
    				return _context.USP_Drzava_DELETE(item.IDDrzava);
    			}	
    									
    			public void Insert(Model.Data.Item.DrzavaItem item)
    			{
    				_context.USP_Drzava_INSERT(item.IDDrzava, item.Naziv, item.NazivKr, item.Kratica, item.NazivEn, item.NazivFr, item.Kod, item.Teritorij, item.IDDrzavaNad, item.SifDrzava, item.OznDrzava, item.ISO3166, item.FIPS104, item.BBAN, item.IBAN, item.Internet, item.OznHr, item.OznEng, item.NazivHr, item.NazivHrDugi, item.NazivEng, item.NazivEngDugi, item.NazivLokal, item.NazivLokalDugi, item.NazivStariHr, item.NazivStariEng, item.Kratica1, item.Nacija, item.Obuhvat, item.Napomena, item.Komentar, item.StsDrzava, item.IzborDrzava, item.ZastavaV, item.ZastavaM, item.ZastavaMPath, item.ZastavaVPath, item.GrbV, item.GrbM, item.GrbVPath, item.GrbMPath, item.KartaV, item.KartaM, item.KartaMPath, item.KartaVPath, item.DrzavaHtml1, item.DrzavaHtml2, item.DrzavaHtml3, item.DrzavaHtml4);
    			}
    
    			public ObjectResult<Model.Data.Drzava> InsertResult(Model.Data.Item.DrzavaItem item)
    			{
    				return _context.USP_Drzava_INSERT(item.IDDrzava, item.Naziv, item.NazivKr, item.Kratica, item.NazivEn, item.NazivFr, item.Kod, item.Teritorij, item.IDDrzavaNad, item.SifDrzava, item.OznDrzava, item.ISO3166, item.FIPS104, item.BBAN, item.IBAN, item.Internet, item.OznHr, item.OznEng, item.NazivHr, item.NazivHrDugi, item.NazivEng, item.NazivEngDugi, item.NazivLokal, item.NazivLokalDugi, item.NazivStariHr, item.NazivStariEng, item.Kratica1, item.Nacija, item.Obuhvat, item.Napomena, item.Komentar, item.StsDrzava, item.IzborDrzava, item.ZastavaV, item.ZastavaM, item.ZastavaMPath, item.ZastavaVPath, item.GrbV, item.GrbM, item.GrbVPath, item.GrbMPath, item.KartaV, item.KartaM, item.KartaMPath, item.KartaVPath, item.DrzavaHtml1, item.DrzavaHtml2, item.DrzavaHtml3, item.DrzavaHtml4);
    			}	
    									
    				
    			public void Select(string IDDrzava)
    			{
    				_context.USP_Drzava_SELECT(IDDrzava);
    			}
    
    					
    			public ObjectResult<Model.Data.Drzava> SelectResult(string IDDrzava)
            	{
                	return _context.USP_Drzava_SELECT(IDDrzava);
            	}			
    				
    			public void Update(Model.Data.Item.DrzavaItem item)
    			{
    				_context.USP_Drzava_UPDATE(item.IDDrzava, item.Naziv, item.NazivKr, item.Kratica, item.NazivEn, item.NazivFr, item.Kod, item.Teritorij, item.IDDrzavaNad, item.SifDrzava, item.OznDrzava, item.ISO3166, item.FIPS104, item.BBAN, item.IBAN, item.Internet, item.OznHr, item.OznEng, item.NazivHr, item.NazivHrDugi, item.NazivEng, item.NazivEngDugi, item.NazivLokal, item.NazivLokalDugi, item.NazivStariHr, item.NazivStariEng, item.Kratica1, item.Nacija, item.Obuhvat, item.Napomena, item.Komentar, item.StsDrzava, item.IzborDrzava, item.ZastavaV, item.ZastavaM, item.ZastavaMPath, item.ZastavaVPath, item.GrbV, item.GrbM, item.GrbVPath, item.GrbMPath, item.KartaV, item.KartaM, item.KartaMPath, item.KartaVPath, item.DrzavaHtml1, item.DrzavaHtml2, item.DrzavaHtml3, item.DrzavaHtml4);
    			}
    
    					
    			public ObjectResult<Model.Data.Drzava> UpdateResult(Model.Data.Item.DrzavaItem item)
    			{
    				return _context.USP_Drzava_UPDATE(item.IDDrzava, item.Naziv, item.NazivKr, item.Kratica, item.NazivEn, item.NazivFr, item.Kod, item.Teritorij, item.IDDrzavaNad, item.SifDrzava, item.OznDrzava, item.ISO3166, item.FIPS104, item.BBAN, item.IBAN, item.Internet, item.OznHr, item.OznEng, item.NazivHr, item.NazivHrDugi, item.NazivEng, item.NazivEngDugi, item.NazivLokal, item.NazivLokalDugi, item.NazivStariHr, item.NazivStariEng, item.Kratica1, item.Nacija, item.Obuhvat, item.Napomena, item.Komentar, item.StsDrzava, item.IzborDrzava, item.ZastavaV, item.ZastavaM, item.ZastavaMPath, item.ZastavaVPath, item.GrbV, item.GrbM, item.GrbVPath, item.GrbMPath, item.KartaV, item.KartaM, item.KartaMPath, item.KartaVPath, item.DrzavaHtml1, item.DrzavaHtml2, item.DrzavaHtml3, item.DrzavaHtml4);
    			}
    										
    		
    #endregion
    	
    }
    
}
