//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InLine.Repository.Data
{
    
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Diagnostics;
    using System.Data.Objects;
    using InLine;
    
    public partial interface IObrazacIP2011A
    {
       		
    		void Delete(Model.Data.Item.ObrazacIP2011AItem item);
    
    			
    		ObjectResult<int?> DeleteResult(Model.Data.Item.ObrazacIP2011AItem item);
            								
    		void Insert(Model.Data.Item.ObrazacIP2011AItem item);
    
    		ObjectResult<Model.Data.ObrazacIP2011A> InsertResult(Model.Data.Item.ObrazacIP2011AItem item);
    										
    			
    		void Select(Nullable<long> ID_ObrazacIP2011A);
    
    			ObjectResult<Model.Data.ObrazacIP2011A> SelectResult(Nullable<long> ID_ObrazacIP2011A);
            				
    			
    		void Update(Model.Data.Item.ObrazacIP2011AItem item);
    
    				
    		ObjectResult<Model.Data.ObrazacIP2011A> UpdateResult (Model.Data.Item.ObrazacIP2011AItem item);
    							
    	
    	Model.Data.ObrazacIP2011A FindID(long id);
    	
    	//IEnumerable <Model.Data.ObrazacIP2011A> GetGridData(string filter, string sort, long? start, long? count, bool customserach = false);
    	IEnumerable <Model.Data.ObrazacIP2011A> GetGridData(string filter, string key, string value, string sort, long? start, long? count, bool customserach = false);
    	
    	long GetCount(string filter, string key, string value, bool customserach = false);
    
    	IEnumerable <Model.Data.ObrazacIP2011A> GetData(List<Model.Data.Field.ObrazacIP2011A> fields, List<Model.Data.Filter.ObrazacIP2011A>  filter, List<Model.Data.Sort.ObrazacIP2011A>  sort, long? start = null, long? count = null);
    
    }
    
}
