//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InLine.Repository.Data.CRUD
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Diagnostics;
    using System.Data.Objects;
    using InLine;
    
    public partial class ObveznicaJavnogDuga
    {
    	#region Fields
        
    	public Model.Data.Context _context;
        
    	#endregion
    
    
    
        #region Constructors
        
    	public ObveznicaJavnogDuga(string connstring)
        {
            _context = new Model.Data.Context(connstring);
        }
        
    	#endregion
    
    
    	#region Methods
       		
    			public void Delete(Model.Data.Item.ObveznicaJavnogDugaItem item)
    			{
    				_context.USP_ObveznicaJavnogDuga_DELETE(item.ID_ObveznicaJavnogDuga);
    			}
    
    				
    			public ObjectResult<int?> DeleteResult(Model.Data.Item.ObveznicaJavnogDugaItem item)
    			{
    				return _context.USP_ObveznicaJavnogDuga_DELETE(item.ID_ObveznicaJavnogDuga);
    			}	
    									
    			public void Insert(Model.Data.Item.ObveznicaJavnogDugaItem item)
    			{
    				_context.USP_ObveznicaJavnogDuga_INSERT(item.Broj, item.Datum, item.DokumentVrsta, item.DokumentGrupa, item.ID_DokumentVr, item.TemeljnicaGodina, item.TemeljnicaVrsta, item.TemeljnicaBroj, item.ID_Temeljnica);
    			}
    
    			public ObjectResult<Model.Data.ObveznicaJavnogDuga> InsertResult(Model.Data.Item.ObveznicaJavnogDugaItem item)
    			{
    				return _context.USP_ObveznicaJavnogDuga_INSERT(item.Broj, item.Datum, item.DokumentVrsta, item.DokumentGrupa, item.ID_DokumentVr, item.TemeljnicaGodina, item.TemeljnicaVrsta, item.TemeljnicaBroj, item.ID_Temeljnica);
    			}	
    									
    				
    			public void Select(Nullable<long> ID_ObveznicaJavnogDuga)
    			{
    				_context.USP_ObveznicaJavnogDuga_SELECT(ID_ObveznicaJavnogDuga);
    			}
    
    					
    			public ObjectResult<Model.Data.ObveznicaJavnogDuga> SelectResult(Nullable<long> ID_ObveznicaJavnogDuga)
            	{
                	return _context.USP_ObveznicaJavnogDuga_SELECT(ID_ObveznicaJavnogDuga);
            	}			
    				
    			public void Update(Model.Data.Item.ObveznicaJavnogDugaItem item)
    			{
    				_context.USP_ObveznicaJavnogDuga_UPDATE(item.ID_ObveznicaJavnogDuga, item.Broj, item.Datum, item.DokumentVrsta, item.DokumentGrupa, item.ID_DokumentVr, item.TemeljnicaGodina, item.TemeljnicaVrsta, item.TemeljnicaBroj, item.ID_Temeljnica);
    			}
    
    					
    			public ObjectResult<Model.Data.ObveznicaJavnogDuga> UpdateResult(Model.Data.Item.ObveznicaJavnogDugaItem item)
    			{
    				return _context.USP_ObveznicaJavnogDuga_UPDATE(item.ID_ObveznicaJavnogDuga, item.Broj, item.Datum, item.DokumentVrsta, item.DokumentGrupa, item.ID_DokumentVr, item.TemeljnicaGodina, item.TemeljnicaVrsta, item.TemeljnicaBroj, item.ID_Temeljnica);
    			}
    										
    		
    #endregion
    	
    }
    
}
