//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InLine.Repository.Data.CRUD
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Diagnostics;
    using System.Data.Objects;
    using InLine;
    
    public partial class OpcinaGrTip
    {
    	#region Fields
        
    	public Model.Data.Context _context;
        
    	#endregion
    
    
    
        #region Constructors
        
    	public OpcinaGrTip(string connstring)
        {
            _context = new Model.Data.Context(connstring);
        }
        
    	#endregion
    
    
    	#region Methods
       		
    			public void Delete(Model.Data.Item.OpcinaGrTipItem item)
    			{
    				_context.USP_OpcinaGrTip_DELETE(item.ID_OpcinaGrTip);
    			}
    
    				
    			public ObjectResult<int?> DeleteResult(Model.Data.Item.OpcinaGrTipItem item)
    			{
    				return _context.USP_OpcinaGrTip_DELETE(item.ID_OpcinaGrTip);
    			}	
    									
    			public void Insert(Model.Data.Item.OpcinaGrTipItem item)
    			{
    				_context.USP_OpcinaGrTip_INSERT(item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Opis, item.StsOpcinaGrTip);
    			}
    
    			public ObjectResult<Model.Data.OpcinaGrTip> InsertResult(Model.Data.Item.OpcinaGrTipItem item)
    			{
    				return _context.USP_OpcinaGrTip_INSERT(item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Opis, item.StsOpcinaGrTip);
    			}	
    									
    				
    			public void Select(Nullable<long> ID_OpcinaGrTip)
    			{
    				_context.USP_OpcinaGrTip_SELECT(ID_OpcinaGrTip);
    			}
    
    					
    			public ObjectResult<Model.Data.OpcinaGrTip> SelectResult(Nullable<long> ID_OpcinaGrTip)
            	{
                	return _context.USP_OpcinaGrTip_SELECT(ID_OpcinaGrTip);
            	}			
    				
    			public void Update(Model.Data.Item.OpcinaGrTipItem item)
    			{
    				_context.USP_OpcinaGrTip_UPDATE(item.ID_OpcinaGrTip, item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Opis, item.StsOpcinaGrTip);
    			}
    
    					
    			public ObjectResult<Model.Data.OpcinaGrTip> UpdateResult(Model.Data.Item.OpcinaGrTipItem item)
    			{
    				return _context.USP_OpcinaGrTip_UPDATE(item.ID_OpcinaGrTip, item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Opis, item.StsOpcinaGrTip);
    			}
    										
    		
    #endregion
    	
    }
    
}
