//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InLine.Repository.Data.CRUD
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Diagnostics;
    using System.Data.Objects;
    using InLine;
    
    public partial class PoslovnaGodinaSubjektGrSubjekt
    {
    	#region Fields
        
    	public Model.Data.Context _context;
        
    	#endregion
    
    
    
        #region Constructors
        
    	public PoslovnaGodinaSubjektGrSubjekt(string connstring)
        {
            _context = new Model.Data.Context(connstring);
        }
        
    	#endregion
    
    
    	#region Methods
       		
    			public void Delete(Model.Data.Item.PoslovnaGodinaSubjektGrSubjektItem item)
    			{
    				_context.USP_PoslovnaGodinaSubjektGrSubjekt_DELETE(item.ID_PoslovnaGodinaSubjektGrSubjekt);
    			}
    
    				
    			public ObjectResult<int?> DeleteResult(Model.Data.Item.PoslovnaGodinaSubjektGrSubjektItem item)
    			{
    				return _context.USP_PoslovnaGodinaSubjektGrSubjekt_DELETE(item.ID_PoslovnaGodinaSubjektGrSubjekt);
    			}	
    									
    			public void Insert(Model.Data.Item.PoslovnaGodinaSubjektGrSubjektItem item)
    			{
    				_context.USP_PoslovnaGodinaSubjektGrSubjekt_INSERT(item.ID_PoslovnaGodinaSubjektGr, item.ID_PoslovnaGodinaSubjekt);
    			}
    
    			public ObjectResult<Model.Data.PoslovnaGodinaSubjektGrSubjekt> InsertResult(Model.Data.Item.PoslovnaGodinaSubjektGrSubjektItem item)
    			{
    				return _context.USP_PoslovnaGodinaSubjektGrSubjekt_INSERT(item.ID_PoslovnaGodinaSubjektGr, item.ID_PoslovnaGodinaSubjekt);
    			}	
    									
    				
    			public void Select(Nullable<long> ID_PoslovnaGodinaSubjektGrSubjekt)
    			{
    				_context.USP_PoslovnaGodinaSubjektGrSubjekt_SELECT(ID_PoslovnaGodinaSubjektGrSubjekt);
    			}
    
    					
    			public ObjectResult<Model.Data.PoslovnaGodinaSubjektGrSubjekt> SelectResult(Nullable<long> ID_PoslovnaGodinaSubjektGrSubjekt)
            	{
                	return _context.USP_PoslovnaGodinaSubjektGrSubjekt_SELECT(ID_PoslovnaGodinaSubjektGrSubjekt);
            	}			
    				
    			public void Update(Model.Data.Item.PoslovnaGodinaSubjektGrSubjektItem item)
    			{
    				_context.USP_PoslovnaGodinaSubjektGrSubjekt_UPDATE(item.ID_PoslovnaGodinaSubjektGrSubjekt, item.ID_PoslovnaGodinaSubjektGr, item.ID_PoslovnaGodinaSubjekt);
    			}
    
    					
    			public ObjectResult<Model.Data.PoslovnaGodinaSubjektGrSubjekt> UpdateResult(Model.Data.Item.PoslovnaGodinaSubjektGrSubjektItem item)
    			{
    				return _context.USP_PoslovnaGodinaSubjektGrSubjekt_UPDATE(item.ID_PoslovnaGodinaSubjektGrSubjekt, item.ID_PoslovnaGodinaSubjektGr, item.ID_PoslovnaGodinaSubjekt);
    			}
    										
    		
    #endregion
    	
    }
    
}
