//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InLine.Repository.Data.CRUD
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Diagnostics;
    using System.Data.Objects;
    using InLine;
    
    public partial class UgovorStanOtkupObrokUplata
    {
    	#region Fields
        
    	public Model.Data.Context _context;
        
    	#endregion
    
    
    
        #region Constructors
        
    	public UgovorStanOtkupObrokUplata(string connstring)
        {
            _context = new Model.Data.Context(connstring);
        }
        
    	#endregion
    
    
    	#region Methods
       		
    			public void Delete(Model.Data.Item.UgovorStanOtkupObrokUplataItem item)
    			{
    				_context.USP_UgovorStanOtkupObrokUplata_DELETE(item.ID_UgovorStanOtkupObrokUplata);
    			}
    
    				
    			public ObjectResult<int?> DeleteResult(Model.Data.Item.UgovorStanOtkupObrokUplataItem item)
    			{
    				return _context.USP_UgovorStanOtkupObrokUplata_DELETE(item.ID_UgovorStanOtkupObrokUplata);
    			}	
    									
    			public void Insert(Model.Data.Item.UgovorStanOtkupObrokUplataItem item)
    			{
    				_context.USP_UgovorStanOtkupObrokUplata_INSERT(item.ID_UgovorStanOtkupObrok, item.Datum, item.IznosZateznaKamataUplata, item.IznosValuta, item.IznosValutaUgovor, item.IznosTecajnaRazlika, item.IznosZateznaKamataPrije, item.IznosKredit, item.IznosKamata, item.IznosKreditRevalorizacija, item.IznosKamataRevalorizacija, item.IznosKreditMoratorij, item.IznosKamataMoratorij, item.IznosKreditMoratorijRevalorizacija, item.IznosKamataMoratorijRevalorizacija, item.IznosJednokratno, item.IznosUcesce, item.IznosPreplata, item.IDValuta, item.TemeljnicaGodina, item.TemeljnicaVrsta, item.TemeljnicaBroj, item.DokumentGrupa, item.DokumentVrsta, item.OsnovicaZateznaKamata, item.DatumZateznaKamata, item.IznosZateznaKamata, item.IznosZateznaKamataDugOstatak, item.IznosObrokDugOstatak, item.BrojUgovor, item.BrojAneks, item.BrojStorno, item.BrojObrok, item.ID_UgovorStanOtkupObrokZateznaKamata, item.BrojObrokZateznaKamata, item.BrojPreplata, item.ID_Racun, item.ID_PlacanjeVr, item.ID_Temeljnica, item.DatumInsert, item.OsobaInsert, item.DatumUpdate, item.OsobaUpdate, item.ID_OsobaInsert, item.ID_OsobaUpdate, item.NeZateznaKamata);
    			}
    
    			public ObjectResult<Model.Data.UgovorStanOtkupObrokUplata> InsertResult(Model.Data.Item.UgovorStanOtkupObrokUplataItem item)
    			{
    				return _context.USP_UgovorStanOtkupObrokUplata_INSERT(item.ID_UgovorStanOtkupObrok, item.Datum, item.IznosZateznaKamataUplata, item.IznosValuta, item.IznosValutaUgovor, item.IznosTecajnaRazlika, item.IznosZateznaKamataPrije, item.IznosKredit, item.IznosKamata, item.IznosKreditRevalorizacija, item.IznosKamataRevalorizacija, item.IznosKreditMoratorij, item.IznosKamataMoratorij, item.IznosKreditMoratorijRevalorizacija, item.IznosKamataMoratorijRevalorizacija, item.IznosJednokratno, item.IznosUcesce, item.IznosPreplata, item.IDValuta, item.TemeljnicaGodina, item.TemeljnicaVrsta, item.TemeljnicaBroj, item.DokumentGrupa, item.DokumentVrsta, item.OsnovicaZateznaKamata, item.DatumZateznaKamata, item.IznosZateznaKamata, item.IznosZateznaKamataDugOstatak, item.IznosObrokDugOstatak, item.BrojUgovor, item.BrojAneks, item.BrojStorno, item.BrojObrok, item.ID_UgovorStanOtkupObrokZateznaKamata, item.BrojObrokZateznaKamata, item.BrojPreplata, item.ID_Racun, item.ID_PlacanjeVr, item.ID_Temeljnica, item.DatumInsert, item.OsobaInsert, item.DatumUpdate, item.OsobaUpdate, item.ID_OsobaInsert, item.ID_OsobaUpdate, item.NeZateznaKamata);
    			}	
    									
    				
    			public void Select(Nullable<long> ID_UgovorStanOtkupObrokUplata)
    			{
    				_context.USP_UgovorStanOtkupObrokUplata_SELECT(ID_UgovorStanOtkupObrokUplata);
    			}
    
    					
    			public ObjectResult<Model.Data.UgovorStanOtkupObrokUplata> SelectResult(Nullable<long> ID_UgovorStanOtkupObrokUplata)
            	{
                	return _context.USP_UgovorStanOtkupObrokUplata_SELECT(ID_UgovorStanOtkupObrokUplata);
            	}			
    				
    			public void Update(Model.Data.Item.UgovorStanOtkupObrokUplataItem item)
    			{
    				_context.USP_UgovorStanOtkupObrokUplata_UPDATE(item.ID_UgovorStanOtkupObrokUplata, item.ID_UgovorStanOtkupObrok, item.Datum, item.IznosZateznaKamataUplata, item.IznosValuta, item.IznosValutaUgovor, item.IznosTecajnaRazlika, item.IznosZateznaKamataPrije, item.IznosKredit, item.IznosKamata, item.IznosKreditRevalorizacija, item.IznosKamataRevalorizacija, item.IznosKreditMoratorij, item.IznosKamataMoratorij, item.IznosKreditMoratorijRevalorizacija, item.IznosKamataMoratorijRevalorizacija, item.IznosJednokratno, item.IznosUcesce, item.IznosPreplata, item.IDValuta, item.TemeljnicaGodina, item.TemeljnicaVrsta, item.TemeljnicaBroj, item.DokumentGrupa, item.DokumentVrsta, item.OsnovicaZateznaKamata, item.DatumZateznaKamata, item.IznosZateznaKamata, item.IznosZateznaKamataDugOstatak, item.IznosObrokDugOstatak, item.BrojUgovor, item.BrojAneks, item.BrojStorno, item.BrojObrok, item.ID_UgovorStanOtkupObrokZateznaKamata, item.BrojObrokZateznaKamata, item.BrojPreplata, item.ID_Racun, item.ID_PlacanjeVr, item.ID_Temeljnica, item.DatumInsert, item.OsobaInsert, item.DatumUpdate, item.OsobaUpdate, item.ID_OsobaInsert, item.ID_OsobaUpdate, item.NeZateznaKamata);
    			}
    
    					
    			public ObjectResult<Model.Data.UgovorStanOtkupObrokUplata> UpdateResult(Model.Data.Item.UgovorStanOtkupObrokUplataItem item)
    			{
    				return _context.USP_UgovorStanOtkupObrokUplata_UPDATE(item.ID_UgovorStanOtkupObrokUplata, item.ID_UgovorStanOtkupObrok, item.Datum, item.IznosZateznaKamataUplata, item.IznosValuta, item.IznosValutaUgovor, item.IznosTecajnaRazlika, item.IznosZateznaKamataPrije, item.IznosKredit, item.IznosKamata, item.IznosKreditRevalorizacija, item.IznosKamataRevalorizacija, item.IznosKreditMoratorij, item.IznosKamataMoratorij, item.IznosKreditMoratorijRevalorizacija, item.IznosKamataMoratorijRevalorizacija, item.IznosJednokratno, item.IznosUcesce, item.IznosPreplata, item.IDValuta, item.TemeljnicaGodina, item.TemeljnicaVrsta, item.TemeljnicaBroj, item.DokumentGrupa, item.DokumentVrsta, item.OsnovicaZateznaKamata, item.DatumZateznaKamata, item.IznosZateznaKamata, item.IznosZateznaKamataDugOstatak, item.IznosObrokDugOstatak, item.BrojUgovor, item.BrojAneks, item.BrojStorno, item.BrojObrok, item.ID_UgovorStanOtkupObrokZateznaKamata, item.BrojObrokZateznaKamata, item.BrojPreplata, item.ID_Racun, item.ID_PlacanjeVr, item.ID_Temeljnica, item.DatumInsert, item.OsobaInsert, item.DatumUpdate, item.OsobaUpdate, item.ID_OsobaInsert, item.ID_OsobaUpdate, item.NeZateznaKamata);
    			}
    										
    		
    #endregion
    	
    }
    
}
