//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InLine.Repository.Data.CRUD
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Diagnostics;
    using System.Data.Objects;
    using InLine;
    
    public partial class ZbrojniNalog
    {
    	#region Fields
        
    	public Model.Data.Context _context;
        
    	#endregion
    
    
    
        #region Constructors
        
    	public ZbrojniNalog(string connstring)
        {
            _context = new Model.Data.Context(connstring);
        }
        
    	#endregion
    
    
    	#region Methods
       		
    			public void Delete(Model.Data.Item.ZbrojniNalogItem item)
    			{
    				_context.USP_ZbrojniNalog_DELETE(item.ID_ZbrojniNalog);
    			}
    
    				
    			public ObjectResult<int?> DeleteResult(Model.Data.Item.ZbrojniNalogItem item)
    			{
    				return _context.USP_ZbrojniNalog_DELETE(item.ID_ZbrojniNalog);
    			}	
    									
    			public void Insert(Model.Data.Item.ZbrojniNalogItem item)
    			{
    				_context.USP_ZbrojniNalog_INSERT(item.ID_Zapis, item.IDZbrojniNalogVerzija, item.DatumPredaje, item.DatumValuta, item.DatotekaNaziv, item.Datoteka);
    			}
    
    			public ObjectResult<Model.Data.ZbrojniNalog> InsertResult(Model.Data.Item.ZbrojniNalogItem item)
    			{
    				return _context.USP_ZbrojniNalog_INSERT(item.ID_Zapis, item.IDZbrojniNalogVerzija, item.DatumPredaje, item.DatumValuta, item.DatotekaNaziv, item.Datoteka);
    			}	
    									
    				
    			public void Select(Nullable<long> ID_ZbrojniNalog)
    			{
    				_context.USP_ZbrojniNalog_SELECT(ID_ZbrojniNalog);
    			}
    
    					
    			public ObjectResult<Model.Data.ZbrojniNalog> SelectResult(Nullable<long> ID_ZbrojniNalog)
            	{
                	return _context.USP_ZbrojniNalog_SELECT(ID_ZbrojniNalog);
            	}			
    				
    			public void Update(Model.Data.Item.ZbrojniNalogItem item)
    			{
    				_context.USP_ZbrojniNalog_UPDATE(item.ID_ZbrojniNalog, item.ID_Zapis, item.IDZbrojniNalogVerzija, item.DatumPredaje, item.DatumValuta, item.DatotekaNaziv, item.Datoteka);
    			}
    
    					
    			public ObjectResult<Model.Data.ZbrojniNalog> UpdateResult(Model.Data.Item.ZbrojniNalogItem item)
    			{
    				return _context.USP_ZbrojniNalog_UPDATE(item.ID_ZbrojniNalog, item.ID_Zapis, item.IDZbrojniNalogVerzija, item.DatumPredaje, item.DatumValuta, item.DatotekaNaziv, item.Datoteka);
    			}
    										
    		
    #endregion
    	
    }
    
}
