//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InLine.Repository.Data.CRUD
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Diagnostics;
    using System.Data.Objects;
    using InLine;
    
    public partial class Zupanija
    {
    	#region Fields
        
    	public Model.Data.Context _context;
        
    	#endregion
    
    
    
        #region Constructors
        
    	public Zupanija(string connstring)
        {
            _context = new Model.Data.Context(connstring);
        }
        
    	#endregion
    
    
    	#region Methods
       		
    			public void Delete(Model.Data.Item.ZupanijaItem item)
    			{
    				_context.USP_Zupanija_DELETE(item.ID_Zupanija);
    			}
    
    				
    			public ObjectResult<int?> DeleteResult(Model.Data.Item.ZupanijaItem item)
    			{
    				return _context.USP_Zupanija_DELETE(item.ID_Zupanija);
    			}	
    									
    			public void Insert(Model.Data.Item.ZupanijaItem item)
    			{
    				_context.USP_Zupanija_INSERT(item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Opis, item.ID_MjestoPosta, item.TelPozBr, item.SjedZup, item.SjedisteZup, item.PathGrb, item.GrbSlika, item.PathKarta, item.KartaSlika, item.KartaSlika2, item.IDDrzava, item.ID_Subjekt, item.OIB);
    			}
    
    			public ObjectResult<Model.Data.Zupanija> InsertResult(Model.Data.Item.ZupanijaItem item)
    			{
    				return _context.USP_Zupanija_INSERT(item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Opis, item.ID_MjestoPosta, item.TelPozBr, item.SjedZup, item.SjedisteZup, item.PathGrb, item.GrbSlika, item.PathKarta, item.KartaSlika, item.KartaSlika2, item.IDDrzava, item.ID_Subjekt, item.OIB);
    			}	
    									
    				
    			public void Select(Nullable<long> ID_Zupanija)
    			{
    				_context.USP_Zupanija_SELECT(ID_Zupanija);
    			}
    
    					
    			public ObjectResult<Model.Data.Zupanija> SelectResult(Nullable<long> ID_Zupanija)
            	{
                	return _context.USP_Zupanija_SELECT(ID_Zupanija);
            	}			
    				
    			public void Update(Model.Data.Item.ZupanijaItem item)
    			{
    				_context.USP_Zupanija_UPDATE(item.ID_Zupanija, item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Opis, item.ID_MjestoPosta, item.TelPozBr, item.SjedZup, item.SjedisteZup, item.PathGrb, item.GrbSlika, item.PathKarta, item.KartaSlika, item.KartaSlika2, item.IDDrzava, item.ID_Subjekt, item.OIB);
    			}
    
    					
    			public ObjectResult<Model.Data.Zupanija> UpdateResult(Model.Data.Item.ZupanijaItem item)
    			{
    				return _context.USP_Zupanija_UPDATE(item.ID_Zupanija, item.Oznaka, item.Naziv, item.NazivKr, item.Kratica, item.Opis, item.ID_MjestoPosta, item.TelPozBr, item.SjedZup, item.SjedisteZup, item.PathGrb, item.GrbSlika, item.PathKarta, item.KartaSlika, item.KartaSlika2, item.IDDrzava, item.ID_Subjekt, item.OIB);
    			}
    										
    		
    #endregion
    	
    }
    
}
