//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class DatotekaVrPoljeTipFormFormattedBase
    {
    	#region Properities
    
        [Required(ErrorMessage = AtributClass.DatotekaVrPoljeTip.ID_DatotekaVrPoljeTip.Required)]
    	[DisplayName(AtributClass.DatotekaVrPoljeTip.ID_DatotekaVrPoljeTip.DisplayName)]
        	public long ID_DatotekaVrPoljeTip { get; set; }
    
    	
        [StringLength(20, ErrorMessage = AtributClass.DatotekaVrPoljeTip.Oznaka.StringLength)]
        [Required(ErrorMessage = AtributClass.DatotekaVrPoljeTip.Oznaka.Required)]
    	[DisplayName(AtributClass.DatotekaVrPoljeTip.Oznaka.DisplayName)]
       	public string Oznaka { get; set; }
    
    	
        [StringLength(255, ErrorMessage = AtributClass.DatotekaVrPoljeTip.Naziv.StringLength)]
        [Required(ErrorMessage = AtributClass.DatotekaVrPoljeTip.Naziv.Required)]
    	[DisplayName(AtributClass.DatotekaVrPoljeTip.Naziv.DisplayName)]
       	public string Naziv { get; set; }
    
    	
        [StringLength(30, ErrorMessage = AtributClass.DatotekaVrPoljeTip.NazivKr.StringLength)]
        [Required(ErrorMessage = AtributClass.DatotekaVrPoljeTip.NazivKr.Required)]
    	[DisplayName(AtributClass.DatotekaVrPoljeTip.NazivKr.DisplayName)]
       	public string NazivKr { get; set; }
    
    	
        [StringLength(10, ErrorMessage = AtributClass.DatotekaVrPoljeTip.Kratica.StringLength)]
        [Required(ErrorMessage = AtributClass.DatotekaVrPoljeTip.Kratica.Required)]
    	[DisplayName(AtributClass.DatotekaVrPoljeTip.Kratica.DisplayName)]
       	public string Kratica { get; set; }
    
    	[DisplayName(AtributClass.DatotekaVrPoljeTip.Velicina.DisplayName)]
       	public Nullable<int> Velicina { get; set; }
    
    	[DisplayName(AtributClass.DatotekaVrPoljeTip.ValueMin.DisplayName)]
       	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DecimalFormat.TockaZarez, ApplyFormatInEditMode = true)]
    	public Nullable<decimal> ValueMin { get; set; }
    
    	[DisplayName(AtributClass.DatotekaVrPoljeTip.ValueMax.DisplayName)]
       	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DecimalFormat.TockaZarez, ApplyFormatInEditMode = true)]
    	public Nullable<decimal> ValueMax { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public DatotekaVrPoljeTipFormFormattedBase()
        { }
    	
    	public DatotekaVrPoljeTipFormFormattedBase(Model.Data.DatotekaVrPoljeTip formformated)
    	{
    	    this.ID_DatotekaVrPoljeTip = formformated.ID_DatotekaVrPoljeTip;
    	    this.Oznaka = formformated.Oznaka;
    	    this.Naziv = formformated.Naziv;
    	    this.NazivKr = formformated.NazivKr;
    	    this.Kratica = formformated.Kratica;
    	    this.Velicina = formformated.Velicina;
    	    this.ValueMin = formformated.ValueMin;
    	    this.ValueMax = formformated.ValueMax;
    	}
    
    	/*
    	    mymodel.ID_DatotekaVrPoljeTip = model.ID_DatotekaVrPoljeTip;
    	    mymodel.Oznaka = model.Oznaka;
    	    mymodel.Naziv = model.Naziv;
    	    mymodel.NazivKr = model.NazivKr;
    	    mymodel.Kratica = model.Kratica;
    	    mymodel.Velicina = model.Velicina;
    	    mymodel.ValueMin = model.ValueMin;
    	    mymodel.ValueMax = model.ValueMax;
    		
    	*/
    
    		#endregion
    	
    }
}
