//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate.AtributClass
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    
    
    public static class DohodakPrimitak
    {
    	
    
    	public static class ID_DohodakPrimitak
    	{
    		public const string Item = "ID_DohodakPrimitak";
    		  public const string DisplayName = "ID_DohodakPrimitak";
    				public const string Required = "*";
     
      		public const string Formatter = "$.ID_DohodakPrimitakFormatter";
    		public const string Sortable = "ID_DohodakPrimitak";
    	}
    
    
    	public static class ID_Dohodak
    	{
    		public const string Item = "ID_Dohodak";
    		  public const string DisplayName = "ID_Dohodak";
    				public const string Required = "*";
    		public const string Formatter = "$.ID_DohodakFormatter";
    		public const string Sortable = "ID_Dohodak";
    	}
    
    
    	public static class ID_Primitak
    	{
    		public const string Item = "ID_Primitak";
    		  public const string DisplayName = "ID_Primitak";
    				public const string Required = "*";
    		public const string Formatter = "$.ID_PrimitakFormatter";
    		public const string Sortable = "ID_Primitak";
    	}
    
    
    	public static class IznosBruto
    	{
    		public const string Item = "IznosBruto";
    		  public const string DisplayName = "IznosBruto";
    				public const string Required = "*";
    		public const string Formatter = "$.IznosBrutoFormatter";
    		public const string Sortable = "IznosBruto";
    	}
    
    
    	public static class IznosDoprinosIz
    	{
    		public const string Item = "IznosDoprinosIz";
    		  public const string DisplayName = "IznosDoprinosIz";
    				public const string Required = "*";
    		public const string Formatter = "$.IznosDoprinosIzFormatter";
    		public const string Sortable = "IznosDoprinosIz";
    	}
    
    
    	public static class IznosDohodak
    	{
    		public const string Item = "IznosDohodak";
    		  public const string DisplayName = "IznosDohodak";
    				public const string Required = "*";
    		public const string Formatter = "$.IznosDohodakFormatter";
    		public const string Sortable = "IznosDohodak";
    	}
    
    
    	public static class IznosPorezOsnova
    	{
    		public const string Item = "IznosPorezOsnova";
    		  public const string DisplayName = "IznosPorezOsnova";
    				public const string Required = "*";
    		public const string Formatter = "$.IznosPorezOsnovaFormatter";
    		public const string Sortable = "IznosPorezOsnova";
    	}
    
    
    	public static class IznosPorez
    	{
    		public const string Item = "IznosPorez";
    		  public const string DisplayName = "IznosPorez";
    				public const string Required = "*";
    		public const string Formatter = "$.IznosPorezFormatter";
    		public const string Sortable = "IznosPorez";
    	}
    
    
    	public static class IznosPrirez
    	{
    		public const string Item = "IznosPrirez";
    		  public const string DisplayName = "IznosPrirez";
    				public const string Required = "*";
    		public const string Formatter = "$.IznosPrirezFormatter";
    		public const string Sortable = "IznosPrirez";
    	}
    
    
    	public static class IznosNeto
    	{
    		public const string Item = "IznosNeto";
    		  public const string DisplayName = "IznosNeto";
    				public const string Required = "*";
    		public const string Formatter = "$.IznosNetoFormatter";
    		public const string Sortable = "IznosNeto";
    	}
    
    
    	public static class IznosNaknada
    	{
    		public const string Item = "IznosNaknada";
    		  public const string DisplayName = "IznosNaknada";
    				public const string Required = "*";
    		public const string Formatter = "$.IznosNaknadaFormatter";
    		public const string Sortable = "IznosNaknada";
    	}
    
    
    }
}
