//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class DohodakPrimateljDavanjeFormFormattedBase
    {
    	#region Properities
    
        [Required(ErrorMessage = AtributClass.DohodakPrimateljDavanje.ID_DohodakPrimateljDavanje.Required)]
    	[DisplayName(AtributClass.DohodakPrimateljDavanje.ID_DohodakPrimateljDavanje.DisplayName)]
        	public long ID_DohodakPrimateljDavanje { get; set; }
    
        [Required(ErrorMessage = AtributClass.DohodakPrimateljDavanje.ID_DohodakPrimatelj.Required)]
    	[DisplayName(AtributClass.DohodakPrimateljDavanje.ID_DohodakPrimatelj.DisplayName)]
       	public long ID_DohodakPrimatelj { get; set; }
    
        [Required(ErrorMessage = AtributClass.DohodakPrimateljDavanje.ID_Davanje.Required)]
    	[DisplayName(AtributClass.DohodakPrimateljDavanje.ID_Davanje.DisplayName)]
       	public long ID_Davanje { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public DohodakPrimateljDavanjeFormFormattedBase()
        { }
    	
    	public DohodakPrimateljDavanjeFormFormattedBase(Model.Data.DohodakPrimateljDavanje formformated)
    	{
    	    this.ID_DohodakPrimateljDavanje = formformated.ID_DohodakPrimateljDavanje;
    	    this.ID_DohodakPrimatelj = formformated.ID_DohodakPrimatelj;
    	    this.ID_Davanje = formformated.ID_Davanje;
    	}
    
    	/*
    	    mymodel.ID_DohodakPrimateljDavanje = model.ID_DohodakPrimateljDavanje;
    	    mymodel.ID_DohodakPrimatelj = model.ID_DohodakPrimatelj;
    	    mymodel.ID_Davanje = model.ID_Davanje;
    		
    	*/
    
    		#endregion
    	
    }
}
