//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.GridFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class DoprinosDohodakGridFormattedBase
    {
    	#region Properities
        [Required(ErrorMessage = AtributClass.DoprinosDohodak.ID_DoprinosDohodak.Required)]
    	[DisplayName(AtributClass.DoprinosDohodak.ID_DoprinosDohodak.DisplayName)]
        [ScaffoldColumn(false)]
      	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.DoprinosDohodak.ID_DoprinosDohodak.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.ID_DoprinosDohodak.Sortable)]
    	public long ID_DoprinosDohodak { get; set; }
    
        [Required(ErrorMessage = AtributClass.DoprinosDohodak.ID_DoprinosDohodakVr.Required)]
    	[DisplayName(AtributClass.DoprinosDohodak.ID_DoprinosDohodakVr.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.DoprinosDohodak.ID_DoprinosDohodakVr.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.ID_DoprinosDohodakVr.Sortable)]
    	public long ID_DoprinosDohodakVr { get; set; }
    
    	[DisplayName(AtributClass.DoprinosDohodak.ID_Davanje.DisplayName)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.DoprinosDohodak.ID_Davanje.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.ID_Davanje.Sortable)]
    	public Nullable<long> ID_Davanje { get; set; }
    
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DatumFormat.ddMMyyyy, ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = AtributClass.DoprinosDohodak.DatumOd.Required)]
    	[DisplayName(AtributClass.DoprinosDohodak.DatumOd.DisplayName)]
       	 [JqGridColumnSearchable(false)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Center)]
    	[JqGridColumnFormatter(AtributClass.DoprinosDohodak.DatumOd.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.DatumOd.Sortable)]
    	public System.DateTime DatumOd { get; set; }
    
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DatumFormat.ddMMyyyy, ApplyFormatInEditMode = true)]
    	[DisplayName(AtributClass.DoprinosDohodak.DatumDo.DisplayName)]
       	 [JqGridColumnSearchable(false)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Center)]
    	[JqGridColumnFormatter(AtributClass.DoprinosDohodak.DatumDo.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.DatumDo.Sortable)]
    	public Nullable<System.DateTime> DatumDo { get; set; }
    
        [Required(ErrorMessage = AtributClass.DoprinosDohodak.Stopa.Required)]
    	[DisplayName(AtributClass.DoprinosDohodak.Stopa.DisplayName)]
       	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DecimalFormat.TockaZarez, ApplyFormatInEditMode = true)]
    	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.DoprinosDohodak.Stopa.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.Stopa.Sortable)]
    	public decimal Stopa { get; set; }
    
        [Required(ErrorMessage = AtributClass.DoprinosDohodak.IzBruto.Required)]
    	[DisplayName(AtributClass.DoprinosDohodak.IzBruto.DisplayName)]
       	[JqGridColumnSearchable(false, KeyWord.FilterGridFormat.BoolFilterDaNe, KeyWord.KontrolerFilteriGridFormat.Filter, SearchType = JqGridColumnSearchTypes.Select, SearchOperators = JqGridSearchOperators.Eq | JqGridSearchOperators.Ne)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Center)]
    	[JqGridColumnFormatter(JqGridColumnPredefinedFormatters.CheckBox)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.IzBruto.Sortable)]
    	public bool IzBruto { get; set; }
    
    	[DisplayName(AtributClass.DoprinosDohodak.IDMirovinskiStup.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.DoprinosDohodak.IDMirovinskiStup.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.IDMirovinskiStup.Sortable)]
    	public Nullable<int> IDMirovinskiStup { get; set; }
    
    	[DisplayName(AtributClass.DoprinosDohodak.IDPoticanjeZaposljavanja.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.DoprinosDohodak.IDPoticanjeZaposljavanja.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.IDPoticanjeZaposljavanja.Sortable)]
    	public Nullable<int> IDPoticanjeZaposljavanja { get; set; }
    
    	[DisplayName(AtributClass.DoprinosDohodak.PrvoZaposlenje.DisplayName)]
       	[JqGridColumnSearchable(false, KeyWord.FilterGridFormat.BoolFilterDaNe, KeyWord.KontrolerFilteriGridFormat.Filter, SearchType = JqGridColumnSearchTypes.Select, SearchOperators = JqGridSearchOperators.Eq | JqGridSearchOperators.Ne)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Center)]
    	[JqGridColumnFormatter(JqGridColumnPredefinedFormatters.CheckBox)]
    	[JqGridColumnSortable(true, Index = AtributClass.DoprinosDohodak.PrvoZaposlenje.Sortable)]
    	public Nullable<bool> PrvoZaposlenje { get; set; }
    
    	#endregion
    	
    	
    	#region Constructor
    	
    	public DoprinosDohodakGridFormattedBase()
        { }
    	
    	public DoprinosDohodakGridFormattedBase(Model.Data.DoprinosDohodak gridformated)
    	{
    	    this.ID_DoprinosDohodak = gridformated.ID_DoprinosDohodak;
    	    this.ID_DoprinosDohodakVr = gridformated.ID_DoprinosDohodakVr;
    	    this.ID_Davanje = gridformated.ID_Davanje;
    	    this.DatumOd = gridformated.DatumOd;
    	    this.DatumDo = gridformated.DatumDo;
    	    this.Stopa = gridformated.Stopa;
    	    this.IzBruto = gridformated.IzBruto;
    	    this.IDMirovinskiStup = gridformated.IDMirovinskiStup;
    	    this.IDPoticanjeZaposljavanja = gridformated.IDPoticanjeZaposljavanja;
    	    this.PrvoZaposlenje = gridformated.PrvoZaposlenje;
    	}
    
    	/*
    	    mymodel.ID_DoprinosDohodak = model.ID_DoprinosDohodak;
    	    mymodel.ID_DoprinosDohodakVr = model.ID_DoprinosDohodakVr;
    	    mymodel.ID_Davanje = model.ID_Davanje;
    	    mymodel.DatumOd = model.DatumOd;
    	    mymodel.DatumDo = model.DatumDo;
    	    mymodel.Stopa = model.Stopa;
    	    mymodel.IzBruto = model.IzBruto;
    	    mymodel.IDMirovinskiStup = model.IDMirovinskiStup;
    	    mymodel.IDPoticanjeZaposljavanja = model.IDPoticanjeZaposljavanja;
    	    mymodel.PrvoZaposlenje = model.PrvoZaposlenje;
    		
    	*/
    
    		#endregion
    }
}
