//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate.AtributClass
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    
    
    public static class Izvod
    {
    	
    
    	public static class ID_Izvod
    	{
    		public const string Item = "ID_Izvod";
    	  public const string DisplayName = "ID_Izvod"; 
    			public const string Required = "*";
     
      		public const string Formatter = "$.ID_IzvodFormatter";
    		public const string Sortable = "ID_Izvod";
    	}
    
    
    	public static class ID_Zapis
    	{
    		public const string Item = "ID_Zapis";
    	  public const string DisplayName = "ID_Zapis"; 
    			public const string Formatter = "$.ID_ZapisFormatter";
    		public const string Sortable = "ID_Zapis";
    	}
    
    
    	public static class IDIzvodVerzija
    	{
    		public const string Item = "IDIzvodVerzija";
    	  public const string DisplayName = "IDIzvodVerzija"; 
    			public const string Required = "*";
    		public const string Formatter = "$.IDIzvodVerzijaFormatter";
    		public const string Sortable = "IDIzvodVerzija";
    	}
    
    
    	public static class IznosDuguje
    	{
    		public const string Item = "IznosDuguje";
    	  public const string DisplayName = "IznosDuguje"; 
    			public const string Formatter = "$.IznosDugujeFormatter";
    		public const string Sortable = "IznosDuguje";
    	}
    
    
    	public static class IznosPotrazuje
    	{
    		public const string Item = "IznosPotrazuje";
    	  public const string DisplayName = "IznosPotrazuje"; 
    			public const string Formatter = "$.IznosPotrazujeFormatter";
    		public const string Sortable = "IznosPotrazuje";
    	}
    
    
    	public static class SaldoStaro
    	{
    		public const string Item = "SaldoStaro";
    	  public const string DisplayName = "SaldoStaro"; 
    			public const string Formatter = "$.SaldoStaroFormatter";
    		public const string Sortable = "SaldoStaro";
    	}
    
    
    	public static class SaldoNovo
    	{
    		public const string Item = "SaldoNovo";
    	  public const string DisplayName = "SaldoNovo"; 
    			public const string Formatter = "$.SaldoNovoFormatter";
    		public const string Sortable = "SaldoNovo";
    	}
    
    
    	public static class ID_SubjektRacun
    	{
    		public const string Item = "ID_SubjektRacun";
    	  public const string DisplayName = "ID_SubjektRacun"; 
    			public const string Formatter = "$.ID_SubjektRacunFormatter";
    		public const string Sortable = "ID_SubjektRacun";
    	}
    
    
    }
}
