//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate.AtributClass
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    
    
    public static class Kalendar
    {
    	
    
    	public static class IDDatum
    	{
    		public const string Item = "IDDatum";
    		  public const string DisplayName = "IDDatum";
    				public const string Required = "*";
    		public const string Formatter = "$.IDDatumFormatter";
    		public const string Sortable = "IDDatum";
    	}
    
    
    	public static class RBR
    	{
    		public const string Item = "RBR";
    		  public const string DisplayName = "RBR";
    				public const string Formatter = "$.RBRFormatter";
    		public const string Sortable = "RBR";
    	}
    
    
    	public static class Datum
    	{
    		public const string Item = "Datum";
    		  public const string DisplayName = "Datum";
    				public const string Formatter = "$.DatumFormatter";
    		public const string Sortable = "Datum";
    	}
    
    
    	public static class Godina
    	{
    		public const string Item = "Godina";
    		  public const string DisplayName = "Godina";
    				public const string Formatter = "$.GodinaFormatter";
    		public const string Sortable = "Godina";
    	}
    
    
    	public static class Mjesec
    	{
    		public const string Item = "Mjesec";
    		  public const string DisplayName = "Mjesec";
    				public const string Formatter = "$.MjesecFormatter";
    		public const string Sortable = "Mjesec";
    	}
    
    
    	public static class Dan
    	{
    		public const string Item = "Dan";
    		  public const string DisplayName = "Dan";
    				public const string Formatter = "$.DanFormatter";
    		public const string Sortable = "Dan";
    	}
    
    
    	public static class Tromjesecje
    	{
    		public const string Item = "Tromjesecje";
    	  public const string DisplayName = "Tromjesecje"; 
    			public const string Formatter = "$.TromjesecjeFormatter";
    		public const string Sortable = "Tromjesecje";
    	}
    
    
    	public static class TjedanUGodini
    	{
    		public const string Item = "TjedanUGodini";
    	  public const string DisplayName = "TjedanUGodini"; 
    			public const string Formatter = "$.TjedanUGodiniFormatter";
    		public const string Sortable = "TjedanUGodini";
    	}
    
    
    	public static class DanUGodini
    	{
    		public const string Item = "DanUGodini";
    	  public const string DisplayName = "DanUGodini"; 
    			public const string Formatter = "$.DanUGodiniFormatter";
    		public const string Sortable = "DanUGodini";
    	}
    
    
    	public static class DanUTjednu
    	{
    		public const string Item = "DanUTjednu";
    	  public const string DisplayName = "DanUTjednu"; 
    			public const string Formatter = "$.DanUTjednuFormatter";
    		public const string Sortable = "DanUTjednu";
    	}
    
    
    }
}
