//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.GridFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class KnjigaOSGridFormattedBase
    {
    	#region Properities
        [Required(ErrorMessage = AtributClass.KnjigaOS.ID_KnjigaOS.Required)]
    	[DisplayName(AtributClass.KnjigaOS.ID_KnjigaOS.DisplayName)]
        [ScaffoldColumn(false)]
      	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.KnjigaOS.ID_KnjigaOS.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.KnjigaOS.ID_KnjigaOS.Sortable)]
    	public long ID_KnjigaOS { get; set; }
    
    	[DisplayName(AtributClass.KnjigaOS.ID_Zapis.DisplayName)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.KnjigaOS.ID_Zapis.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.KnjigaOS.ID_Zapis.Sortable)]
    	public Nullable<long> ID_Zapis { get; set; }
    
        [Required(ErrorMessage = AtributClass.KnjigaOS.ID_PoslovniSubjekt.Required)]
    	[DisplayName(AtributClass.KnjigaOS.ID_PoslovniSubjekt.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.KnjigaOS.ID_PoslovniSubjekt.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.KnjigaOS.ID_PoslovniSubjekt.Sortable)]
    	public long ID_PoslovniSubjekt { get; set; }
    
    	#endregion
    	
    	
    	#region Constructor
    	
    	public KnjigaOSGridFormattedBase()
        { }
    	
    	public KnjigaOSGridFormattedBase(Model.Data.KnjigaOS gridformated)
    	{
    	    this.ID_KnjigaOS = gridformated.ID_KnjigaOS;
    	    this.ID_Zapis = gridformated.ID_Zapis;
    	    this.ID_PoslovniSubjekt = gridformated.ID_PoslovniSubjekt;
    	}
    
    	/*
    	    mymodel.ID_KnjigaOS = model.ID_KnjigaOS;
    	    mymodel.ID_Zapis = model.ID_Zapis;
    	    mymodel.ID_PoslovniSubjekt = model.ID_PoslovniSubjekt;
    		
    	*/
    
    		#endregion
    }
}
