//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class PorezDohodakFormFormattedBase
    {
    	#region Properities
    
        [Required(ErrorMessage = AtributClass.PorezDohodak.ID_PorezDohodak.Required)]
    	[DisplayName(AtributClass.PorezDohodak.ID_PorezDohodak.DisplayName)]
        	public long ID_PorezDohodak { get; set; }
    
        [Required(ErrorMessage = AtributClass.PorezDohodak.ID_PorezDohodakVr.Required)]
    	[DisplayName(AtributClass.PorezDohodak.ID_PorezDohodakVr.DisplayName)]
       	public long ID_PorezDohodakVr { get; set; }
    
    	[DisplayName(AtributClass.PorezDohodak.ID_Davanje.DisplayName)]
       	public Nullable<long> ID_Davanje { get; set; }
    
        [Required(ErrorMessage = AtributClass.PorezDohodak.Stopa.Required)]
    	[Range(0.001, int.MaxValue, ErrorMessage = KeyWord.FormaterRazno.RangeErrorPoruka.RangeRequired)]
    	[DisplayName(AtributClass.PorezDohodak.Stopa.DisplayName)]
       	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DecimalFormat.TockaZarez, ApplyFormatInEditMode = true)]
    	public decimal Stopa { get; set; }
    
        [Required(ErrorMessage = AtributClass.PorezDohodak.IznosOsnovaOd.Required)]
    	[Range(0.001, int.MaxValue, ErrorMessage = KeyWord.FormaterRazno.RangeErrorPoruka.RangeRequired)]
    	[DisplayName(AtributClass.PorezDohodak.IznosOsnovaOd.DisplayName)]
       	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DecimalFormat.TockaZarez, ApplyFormatInEditMode = true)]
    	public decimal IznosOsnovaOd { get; set; }
    
    	[DisplayName(AtributClass.PorezDohodak.IznosOsnovaDo.DisplayName)]
       	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DecimalFormat.TockaZarez, ApplyFormatInEditMode = true)]
    	public Nullable<decimal> IznosOsnovaDo { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public PorezDohodakFormFormattedBase()
        { }
    	
    	public PorezDohodakFormFormattedBase(Model.Data.PorezDohodak formformated)
    	{
    	    this.ID_PorezDohodak = formformated.ID_PorezDohodak;
    	    this.ID_PorezDohodakVr = formformated.ID_PorezDohodakVr;
    	    this.ID_Davanje = formformated.ID_Davanje;
    	    this.Stopa = formformated.Stopa;
    	    this.IznosOsnovaOd = formformated.IznosOsnovaOd;
    	    this.IznosOsnovaDo = formformated.IznosOsnovaDo;
    	}
    
    	/*
    	    mymodel.ID_PorezDohodak = model.ID_PorezDohodak;
    	    mymodel.ID_PorezDohodakVr = model.ID_PorezDohodakVr;
    	    mymodel.ID_Davanje = model.ID_Davanje;
    	    mymodel.Stopa = model.Stopa;
    	    mymodel.IznosOsnovaOd = model.IznosOsnovaOd;
    	    mymodel.IznosOsnovaDo = model.IznosOsnovaDo;
    		
    	*/
    
    		#endregion
    	
    }
}
