//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class PraznikPraviloPomakFormFormattedBase
    {
    	#region Properities
    
        [Required(ErrorMessage = AtributClass.PraznikPraviloPomak.ID_PraznikPraviloPomak.Required)]
    	[DisplayName(AtributClass.PraznikPraviloPomak.ID_PraznikPraviloPomak.DisplayName)]
        	public long ID_PraznikPraviloPomak { get; set; }
    
        [Required(ErrorMessage = AtributClass.PraznikPraviloPomak.ID_PraznikPravilo.Required)]
    	[DisplayName(AtributClass.PraznikPraviloPomak.ID_PraznikPravilo.DisplayName)]
       	public long ID_PraznikPravilo { get; set; }
    
    	
        [StringLength(20, ErrorMessage = AtributClass.PraznikPraviloPomak.Oznaka.StringLength)]
        [Required(ErrorMessage = AtributClass.PraznikPraviloPomak.Oznaka.Required)]
    	[DisplayName(AtributClass.PraznikPraviloPomak.Oznaka.DisplayName)]
       	public string Oznaka { get; set; }
    
    	
        [StringLength(255, ErrorMessage = AtributClass.PraznikPraviloPomak.Naziv.StringLength)]
        [Required(ErrorMessage = AtributClass.PraznikPraviloPomak.Naziv.Required)]
    	[DisplayName(AtributClass.PraznikPraviloPomak.Naziv.DisplayName)]
       	public string Naziv { get; set; }
    
    	[DisplayName(AtributClass.PraznikPraviloPomak.TjedanDan.DisplayName)]
       	public Nullable<int> TjedanDan { get; set; }
    
    	[DisplayName(AtributClass.PraznikPraviloPomak.TjedanDanPomak.DisplayName)]
       	public Nullable<int> TjedanDanPomak { get; set; }
    
    	[DisplayName(AtributClass.PraznikPraviloPomak.ID_Praznik.DisplayName)]
       	public Nullable<long> ID_Praznik { get; set; }
    
    	[DisplayName(AtributClass.PraznikPraviloPomak.ID_PraznikPomak.DisplayName)]
       	public Nullable<long> ID_PraznikPomak { get; set; }
    
    	[DisplayName(AtributClass.PraznikPraviloPomak.Broj.DisplayName)]
       	public Nullable<int> Broj { get; set; }
    
    	
        [StringLength(2, ErrorMessage = AtributClass.PraznikPraviloPomak.VremenskiOperator.StringLength)]
    	[DisplayName(AtributClass.PraznikPraviloPomak.VremenskiOperator.DisplayName)]
       	public string VremenskiOperator { get; set; }
    
        [Required(ErrorMessage = AtributClass.PraznikPraviloPomak.Odbaci.Required)]
    	[DisplayName(AtributClass.PraznikPraviloPomak.Odbaci.DisplayName)]
       	public bool Odbaci { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public PraznikPraviloPomakFormFormattedBase()
        { }
    	
    	public PraznikPraviloPomakFormFormattedBase(Model.Data.PraznikPraviloPomak formformated)
    	{
    	    this.ID_PraznikPraviloPomak = formformated.ID_PraznikPraviloPomak;
    	    this.ID_PraznikPravilo = formformated.ID_PraznikPravilo;
    	    this.Oznaka = formformated.Oznaka;
    	    this.Naziv = formformated.Naziv;
    	    this.TjedanDan = formformated.TjedanDan;
    	    this.TjedanDanPomak = formformated.TjedanDanPomak;
    	    this.ID_Praznik = formformated.ID_Praznik;
    	    this.ID_PraznikPomak = formformated.ID_PraznikPomak;
    	    this.Broj = formformated.Broj;
    	    this.VremenskiOperator = formformated.VremenskiOperator;
    	    this.Odbaci = formformated.Odbaci;
    	}
    
    	/*
    	    mymodel.ID_PraznikPraviloPomak = model.ID_PraznikPraviloPomak;
    	    mymodel.ID_PraznikPravilo = model.ID_PraznikPravilo;
    	    mymodel.Oznaka = model.Oznaka;
    	    mymodel.Naziv = model.Naziv;
    	    mymodel.TjedanDan = model.TjedanDan;
    	    mymodel.TjedanDanPomak = model.TjedanDanPomak;
    	    mymodel.ID_Praznik = model.ID_Praznik;
    	    mymodel.ID_PraznikPomak = model.ID_PraznikPomak;
    	    mymodel.Broj = model.Broj;
    	    mymodel.VremenskiOperator = model.VremenskiOperator;
    	    mymodel.Odbaci = model.Odbaci;
    		
    	*/
    
    		#endregion
    	
    }
}
