//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class PrimitakGrPrimitakFormFormattedBase
    {
    	#region Properities
    
        [Required(ErrorMessage = AtributClass.PrimitakGrPrimitak.ID_PrimitakGrPrimitak.Required)]
    	[DisplayName(AtributClass.PrimitakGrPrimitak.ID_PrimitakGrPrimitak.DisplayName)]
        	public long ID_PrimitakGrPrimitak { get; set; }
    
        [Required(ErrorMessage = AtributClass.PrimitakGrPrimitak.ID_PrimitakGr.Required)]
    	[DisplayName(AtributClass.PrimitakGrPrimitak.ID_PrimitakGr.DisplayName)]
       	public long ID_PrimitakGr { get; set; }
    
        [Required(ErrorMessage = AtributClass.PrimitakGrPrimitak.ID_Primitak.Required)]
    	[DisplayName(AtributClass.PrimitakGrPrimitak.ID_Primitak.DisplayName)]
       	public long ID_Primitak { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public PrimitakGrPrimitakFormFormattedBase()
        { }
    	
    	public PrimitakGrPrimitakFormFormattedBase(Model.Data.PrimitakGrPrimitak formformated)
    	{
    	    this.ID_PrimitakGrPrimitak = formformated.ID_PrimitakGrPrimitak;
    	    this.ID_PrimitakGr = formformated.ID_PrimitakGr;
    	    this.ID_Primitak = formformated.ID_Primitak;
    	}
    
    	/*
    	    mymodel.ID_PrimitakGrPrimitak = model.ID_PrimitakGrPrimitak;
    	    mymodel.ID_PrimitakGr = model.ID_PrimitakGr;
    	    mymodel.ID_Primitak = model.ID_Primitak;
    		
    	*/
    
    		#endregion
    	
    }
}
