//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.GridFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class PrimitakGrPrimitakGridFormattedBase
    {
    	#region Properities
        [Required(ErrorMessage = AtributClass.PrimitakGrPrimitak.ID_PrimitakGrPrimitak.Required)]
    	[DisplayName(AtributClass.PrimitakGrPrimitak.ID_PrimitakGrPrimitak.DisplayName)]
        [ScaffoldColumn(false)]
      	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.PrimitakGrPrimitak.ID_PrimitakGrPrimitak.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.PrimitakGrPrimitak.ID_PrimitakGrPrimitak.Sortable)]
    	public long ID_PrimitakGrPrimitak { get; set; }
    
        [Required(ErrorMessage = AtributClass.PrimitakGrPrimitak.ID_PrimitakGr.Required)]
    	[DisplayName(AtributClass.PrimitakGrPrimitak.ID_PrimitakGr.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.PrimitakGrPrimitak.ID_PrimitakGr.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.PrimitakGrPrimitak.ID_PrimitakGr.Sortable)]
    	public long ID_PrimitakGr { get; set; }
    
        [Required(ErrorMessage = AtributClass.PrimitakGrPrimitak.ID_Primitak.Required)]
    	[DisplayName(AtributClass.PrimitakGrPrimitak.ID_Primitak.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.PrimitakGrPrimitak.ID_Primitak.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.PrimitakGrPrimitak.ID_Primitak.Sortable)]
    	public long ID_Primitak { get; set; }
    
    	#endregion
    	
    	
    	#region Constructor
    	
    	public PrimitakGrPrimitakGridFormattedBase()
        { }
    	
    	public PrimitakGrPrimitakGridFormattedBase(Model.Data.PrimitakGrPrimitak gridformated)
    	{
    	    this.ID_PrimitakGrPrimitak = gridformated.ID_PrimitakGrPrimitak;
    	    this.ID_PrimitakGr = gridformated.ID_PrimitakGr;
    	    this.ID_Primitak = gridformated.ID_Primitak;
    	}
    
    	/*
    	    mymodel.ID_PrimitakGrPrimitak = model.ID_PrimitakGrPrimitak;
    	    mymodel.ID_PrimitakGr = model.ID_PrimitakGr;
    	    mymodel.ID_Primitak = model.ID_Primitak;
    		
    	*/
    
    		#endregion
    }
}
