//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.GridFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class RacunUlazKontniPlanGridFormattedBase
    {
    	#region Properities
        [Required(ErrorMessage = AtributClass.RacunUlazKontniPlan.ID_RacunUlazKontniPlan.Required)]
    	[DisplayName(AtributClass.RacunUlazKontniPlan.ID_RacunUlazKontniPlan.DisplayName)]
        [ScaffoldColumn(false)]
      	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.RacunUlazKontniPlan.ID_RacunUlazKontniPlan.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.RacunUlazKontniPlan.ID_RacunUlazKontniPlan.Sortable)]
    	public long ID_RacunUlazKontniPlan { get; set; }
    
        [Required(ErrorMessage = AtributClass.RacunUlazKontniPlan.ID_RacunUlaz.Required)]
    	[DisplayName(AtributClass.RacunUlazKontniPlan.ID_RacunUlaz.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.RacunUlazKontniPlan.ID_RacunUlaz.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.RacunUlazKontniPlan.ID_RacunUlaz.Sortable)]
    	public long ID_RacunUlaz { get; set; }
    
        [Required(ErrorMessage = AtributClass.RacunUlazKontniPlan.ID_KontniPlan.Required)]
    	[DisplayName(AtributClass.RacunUlazKontniPlan.ID_KontniPlan.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.RacunUlazKontniPlan.ID_KontniPlan.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.RacunUlazKontniPlan.ID_KontniPlan.Sortable)]
    	public long ID_KontniPlan { get; set; }
    
        [Required(ErrorMessage = AtributClass.RacunUlazKontniPlan.ID_Shema.Required)]
    	[DisplayName(AtributClass.RacunUlazKontniPlan.ID_Shema.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.RacunUlazKontniPlan.ID_Shema.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.RacunUlazKontniPlan.ID_Shema.Sortable)]
    	public long ID_Shema { get; set; }
    
    	[DisplayName(AtributClass.RacunUlazKontniPlan.ID_KontniPlanAnalitika.DisplayName)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.RacunUlazKontniPlan.ID_KontniPlanAnalitika.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.RacunUlazKontniPlan.ID_KontniPlanAnalitika.Sortable)]
    	public Nullable<long> ID_KontniPlanAnalitika { get; set; }
    
    	#endregion
    	
    	
    	#region Constructor
    	
    	public RacunUlazKontniPlanGridFormattedBase()
        { }
    	
    	public RacunUlazKontniPlanGridFormattedBase(Model.Data.RacunUlazKontniPlan gridformated)
    	{
    	    this.ID_RacunUlazKontniPlan = gridformated.ID_RacunUlazKontniPlan;
    	    this.ID_RacunUlaz = gridformated.ID_RacunUlaz;
    	    this.ID_KontniPlan = gridformated.ID_KontniPlan;
    	    this.ID_Shema = gridformated.ID_Shema;
    	    this.ID_KontniPlanAnalitika = gridformated.ID_KontniPlanAnalitika;
    	}
    
    	/*
    	    mymodel.ID_RacunUlazKontniPlan = model.ID_RacunUlazKontniPlan;
    	    mymodel.ID_RacunUlaz = model.ID_RacunUlaz;
    	    mymodel.ID_KontniPlan = model.ID_KontniPlan;
    	    mymodel.ID_Shema = model.ID_Shema;
    	    mymodel.ID_KontniPlanAnalitika = model.ID_KontniPlanAnalitika;
    		
    	*/
    
    		#endregion
    }
}
