//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class ValutaFormFormattedBase
    {
    	#region Properities
    
    	
        [StringLength(3, ErrorMessage = AtributClass.Valuta.IDValuta.StringLength)]
        [Required(ErrorMessage = AtributClass.Valuta.IDValuta.Required)]
    	[DisplayName(AtributClass.Valuta.IDValuta.DisplayName)]
       	public string IDValuta { get; set; }
    
    	
        [StringLength(255, ErrorMessage = AtributClass.Valuta.Naziv.StringLength)]
        [Required(ErrorMessage = AtributClass.Valuta.Naziv.Required)]
    	[DisplayName(AtributClass.Valuta.Naziv.DisplayName)]
       	public string Naziv { get; set; }
    
    	
        [StringLength(30, ErrorMessage = AtributClass.Valuta.NazivKr.StringLength)]
        [Required(ErrorMessage = AtributClass.Valuta.NazivKr.Required)]
    	[DisplayName(AtributClass.Valuta.NazivKr.DisplayName)]
       	public string NazivKr { get; set; }
    
    	
        [StringLength(10, ErrorMessage = AtributClass.Valuta.Kratica.StringLength)]
        [Required(ErrorMessage = AtributClass.Valuta.Kratica.Required)]
    	[DisplayName(AtributClass.Valuta.Kratica.DisplayName)]
       	public string Kratica { get; set; }
    
    	
        [StringLength(10, ErrorMessage = AtributClass.Valuta.Kratica2.StringLength)]
    	[DisplayName(AtributClass.Valuta.Kratica2.DisplayName)]
       	public string Kratica2 { get; set; }
    
        [Required(ErrorMessage = AtributClass.Valuta.Kod.Required)]
    	[DisplayName(AtributClass.Valuta.Kod.DisplayName)]
       	public int Kod { get; set; }
    
        [Required(ErrorMessage = AtributClass.Valuta.Decimale.Required)]
    	[DisplayName(AtributClass.Valuta.Decimale.DisplayName)]
       	public int Decimale { get; set; }
    
    	
        [StringLength(50, ErrorMessage = AtributClass.Valuta.NazivDio.StringLength)]
        [Required(ErrorMessage = AtributClass.Valuta.NazivDio.Required)]
    	[DisplayName(AtributClass.Valuta.NazivDio.DisplayName)]
       	public string NazivDio { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public ValutaFormFormattedBase()
        { }
    	
    	public ValutaFormFormattedBase(Model.Data.Valuta formformated)
    	{
    	    this.IDValuta = formformated.IDValuta;
    	    this.Naziv = formformated.Naziv;
    	    this.NazivKr = formformated.NazivKr;
    	    this.Kratica = formformated.Kratica;
    	    this.Kratica2 = formformated.Kratica2;
    	    this.Kod = formformated.Kod;
    	    this.Decimale = formformated.Decimale;
    	    this.NazivDio = formformated.NazivDio;
    	}
    
    	/*
    	    mymodel.IDValuta = model.IDValuta;
    	    mymodel.Naziv = model.Naziv;
    	    mymodel.NazivKr = model.NazivKr;
    	    mymodel.Kratica = model.Kratica;
    	    mymodel.Kratica2 = model.Kratica2;
    	    mymodel.Kod = model.Kod;
    	    mymodel.Decimale = model.Decimale;
    	    mymodel.NazivDio = model.NazivDio;
    		
    	*/
    
    		#endregion
    	
    }
}
