//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class ValutaRadnaFormFormattedBase
    {
    	#region Properities
    
        [Required(ErrorMessage = AtributClass.ValutaRadna.ID_Valuta.Required)]
    	[DisplayName(AtributClass.ValutaRadna.ID_Valuta.DisplayName)]
        	public long ID_Valuta { get; set; }
    
    	
        [StringLength(3, ErrorMessage = AtributClass.ValutaRadna.Oznaka.StringLength)]
        [Required(ErrorMessage = AtributClass.ValutaRadna.Oznaka.Required)]
    	[DisplayName(AtributClass.ValutaRadna.Oznaka.DisplayName)]
       	public string Oznaka { get; set; }
    
    	
        [StringLength(255, ErrorMessage = AtributClass.ValutaRadna.Naziv.StringLength)]
        [Required(ErrorMessage = AtributClass.ValutaRadna.Naziv.Required)]
    	[DisplayName(AtributClass.ValutaRadna.Naziv.DisplayName)]
       	public string Naziv { get; set; }
    
    	
        [StringLength(30, ErrorMessage = AtributClass.ValutaRadna.NazivKr.StringLength)]
        [Required(ErrorMessage = AtributClass.ValutaRadna.NazivKr.Required)]
    	[DisplayName(AtributClass.ValutaRadna.NazivKr.DisplayName)]
       	public string NazivKr { get; set; }
    
    	
        [StringLength(10, ErrorMessage = AtributClass.ValutaRadna.Kratica.StringLength)]
        [Required(ErrorMessage = AtributClass.ValutaRadna.Kratica.Required)]
    	[DisplayName(AtributClass.ValutaRadna.Kratica.DisplayName)]
       	public string Kratica { get; set; }
    
    	
        [StringLength(10, ErrorMessage = AtributClass.ValutaRadna.Kratica2.StringLength)]
    	[DisplayName(AtributClass.ValutaRadna.Kratica2.DisplayName)]
       	public string Kratica2 { get; set; }
    
        [Required(ErrorMessage = AtributClass.ValutaRadna.Kod.Required)]
    	[DisplayName(AtributClass.ValutaRadna.Kod.DisplayName)]
       	public int Kod { get; set; }
    
        [Required(ErrorMessage = AtributClass.ValutaRadna.Decimale.Required)]
    	[DisplayName(AtributClass.ValutaRadna.Decimale.DisplayName)]
       	public int Decimale { get; set; }
    
    	
        [StringLength(50, ErrorMessage = AtributClass.ValutaRadna.NazivDio.StringLength)]
        [Required(ErrorMessage = AtributClass.ValutaRadna.NazivDio.Required)]
    	[DisplayName(AtributClass.ValutaRadna.NazivDio.DisplayName)]
       	public string NazivDio { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public ValutaRadnaFormFormattedBase()
        { }
    	
    	public ValutaRadnaFormFormattedBase(Model.Data.ValutaRadna formformated)
    	{
    	    this.ID_Valuta = formformated.ID_Valuta;
    	    this.Oznaka = formformated.Oznaka;
    	    this.Naziv = formformated.Naziv;
    	    this.NazivKr = formformated.NazivKr;
    	    this.Kratica = formformated.Kratica;
    	    this.Kratica2 = formformated.Kratica2;
    	    this.Kod = formformated.Kod;
    	    this.Decimale = formformated.Decimale;
    	    this.NazivDio = formformated.NazivDio;
    	}
    
    	/*
    	    mymodel.ID_Valuta = model.ID_Valuta;
    	    mymodel.Oznaka = model.Oznaka;
    	    mymodel.Naziv = model.Naziv;
    	    mymodel.NazivKr = model.NazivKr;
    	    mymodel.Kratica = model.Kratica;
    	    mymodel.Kratica2 = model.Kratica2;
    	    mymodel.Kod = model.Kod;
    	    mymodel.Decimale = model.Decimale;
    	    mymodel.NazivDio = model.NazivDio;
    		
    	*/
    
    		#endregion
    	
    }
}
