//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate.View.AtributClass
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    
    
    public static class GlavnaKnjigaKontniPlanKontniPlanSt
    {
    	
    
    	public static class ID_GlavnaKnjiga
    	{
    		public const string Item = "ID_GlavnaKnjiga";
    	  public const string DisplayName = "ID_GlavnaKnjiga"; 
    			public const string Required = "*";
    		public const string Formatter = "$.ID_GlavnaKnjigaFormatter";
    		public const string Sortable = "ID_GlavnaKnjiga";
    	}
    
    
    	public static class ID_KontniPlan
    	{
    		public const string Item = "ID_KontniPlan";
    	  public const string DisplayName = "ID_KontniPlan"; 
    			public const string Formatter = "$.ID_KontniPlanFormatter";
    		public const string Sortable = "ID_KontniPlan";
    	}
    
    
    	public static class ID_KontniPlanSt
    	{
    		public const string Item = "ID_KontniPlanSt";
    	  public const string DisplayName = "ID_KontniPlanSt"; 
    			public const string Formatter = "$.ID_KontniPlanStFormatter";
    		public const string Sortable = "ID_KontniPlanSt";
    	}
    
    
    	public static class Naziv
    	{
    		public const string Item = "Naziv";
    	  public const string DisplayName = "Naziv"; 
    		public const string StringLength = "Najveći broj znakova je 255";
    		public const string Formatter = "$.NazivFormatter";
    		public const string Sortable = "Naziv";
    	}
    
    
    	public static class Konto
    	{
    		public const string Item = "Konto";
    	  public const string DisplayName = "Konto"; 
    		public const string StringLength = "Najveći broj znakova je 30";
    		public const string Formatter = "$.KontoFormatter";
    		public const string Sortable = "Konto";
    	}
    
    
    	public static class SaldoKonti
    	{
    		public const string Item = "SaldoKonti";
    	  public const string DisplayName = "SaldoKonti"; 
    			public const string Required = "*";
    		public const string Formatter = "$.SaldoKontiFormatter";
    		public const string Sortable = "SaldoKonti";
    	}
    
    
    	public static class Zapis
    	{
    		public const string Item = "Zapis";
    	  public const string DisplayName = "Zapis"; 
    			public const string Required = "*";
    		public const string Formatter = "$.ZapisFormatter";
    		public const string Sortable = "Zapis";
    	}
    
    
    	public static class Subjekt
    	{
    		public const string Item = "Subjekt";
    	  public const string DisplayName = "Subjekt"; 
    			public const string Required = "*";
    		public const string Formatter = "$.SubjektFormatter";
    		public const string Sortable = "Subjekt";
    	}
    
    
    	public static class Objekt
    	{
    		public const string Item = "Objekt";
    	  public const string DisplayName = "Objekt"; 
    			public const string Required = "*";
    		public const string Formatter = "$.ObjektFormatter";
    		public const string Sortable = "Objekt";
    	}
    
    
    	public static class Davanje
    	{
    		public const string Item = "Davanje";
    	  public const string DisplayName = "Davanje"; 
    			public const string Required = "*";
    		public const string Formatter = "$.DavanjeFormatter";
    		public const string Sortable = "Davanje";
    	}
    
    
    	public static class AnalitikaOd
    	{
    		public const string Item = "AnalitikaOd";
    	  public const string DisplayName = "AnalitikaOd"; 
    			public const string Formatter = "$.AnalitikaOdFormatter";
    		public const string Sortable = "AnalitikaOd";
    	}
    
    
    }
}
