//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate.View
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.GridFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class UgovorStanOtkupKupacDetaljGridFormattedBase
    {
    	#region Properities
        [Required(ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.ID_Kupac.Required)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.ID_Kupac.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.ID_Kupac.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.ID_Kupac.Sortable)]
    	public long ID_Kupac { get; set; }
    
    	
        [StringLength(20, ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.Oznaka.StringLength)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.Oznaka.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.TextOperators)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Left)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.Oznaka.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.Oznaka.Sortable)]
    	public string Oznaka { get; set; }
    
    	
        [StringLength(50, ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.Naziv.StringLength)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.Naziv.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.TextOperators)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Left)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.Naziv.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.Naziv.Sortable)]
    	public string Naziv { get; set; }
    
    	
        [StringLength(13, ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.JMBG.StringLength)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.JMBG.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.TextOperators)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Left)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.JMBG.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.JMBG.Sortable)]
    	public string JMBG { get; set; }
    
    	
        [StringLength(50, ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.Ulica.StringLength)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.Ulica.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.TextOperators)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Left)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.Ulica.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.Ulica.Sortable)]
    	public string Ulica { get; set; }
    
    	
        [StringLength(3, ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.KucniBroj.StringLength)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.KucniBroj.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.TextOperators)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Left)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.KucniBroj.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.KucniBroj.Sortable)]
    	public string KucniBroj { get; set; }
    
    	
        [StringLength(2, ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.KucniBrojDodatak.StringLength)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.KucniBrojDodatak.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.TextOperators)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Left)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.KucniBrojDodatak.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.KucniBrojDodatak.Sortable)]
    	public string KucniBrojDodatak { get; set; }
    
    	
        [StringLength(5, ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.PostanskiBroj.StringLength)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.PostanskiBroj.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.TextOperators)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Left)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.PostanskiBroj.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.PostanskiBroj.Sortable)]
    	public string PostanskiBroj { get; set; }
    
    	
        [StringLength(13, ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.OIB.StringLength)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.OIB.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.TextOperators)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Left)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.OIB.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.OIB.Sortable)]
    	public string OIB { get; set; }
    
    	
        [StringLength(50, ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.Posta.StringLength)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.Posta.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.TextOperators)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Left)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.Posta.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.Posta.Sortable)]
    	public string Posta { get; set; }
    
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.ID_Posta.DisplayName)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.ID_Posta.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.ID_Posta.Sortable)]
    	public Nullable<long> ID_Posta { get; set; }
    
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.ID_Subjekt.DisplayName)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.ID_Subjekt.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.ID_Subjekt.Sortable)]
    	public Nullable<long> ID_Subjekt { get; set; }
    
        [Required(ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.ID_UgovorStanOtkupKupac.Required)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.ID_UgovorStanOtkupKupac.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.ID_UgovorStanOtkupKupac.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.ID_UgovorStanOtkupKupac.Sortable)]
    	public long ID_UgovorStanOtkupKupac { get; set; }
    
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.Nositelj.DisplayName)]
       	[JqGridColumnSearchable(false, KeyWord.FilterGridFormat.BoolFilterDaNe, KeyWord.KontrolerFilteriGridFormat.Filter, SearchType = JqGridColumnSearchTypes.Select, SearchOperators = JqGridSearchOperators.Eq | JqGridSearchOperators.Ne)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Center)]
    	[JqGridColumnFormatter(JqGridColumnPredefinedFormatters.CheckBox)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.Nositelj.Sortable)]
    	public Nullable<bool> Nositelj { get; set; }
    
        [Required(ErrorMessage = AtributClass.UgovorStanOtkupKupacDetalj.ID_UgovorStanOtkup.Required)]
    	[DisplayName(AtributClass.UgovorStanOtkupKupacDetalj.ID_UgovorStanOtkup.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.UgovorStanOtkupKupacDetalj.ID_UgovorStanOtkup.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.UgovorStanOtkupKupacDetalj.ID_UgovorStanOtkup.Sortable)]
    	public long ID_UgovorStanOtkup { get; set; }
    
    	#endregion
    	
    	
    	#region Constructor
    	
    	public UgovorStanOtkupKupacDetaljGridFormattedBase()
        { }
    	
    	public UgovorStanOtkupKupacDetaljGridFormattedBase(Model.Data.View.UgovorStanOtkupKupacDetalj gridformated)
    	{
    	    this.ID_Kupac = gridformated.ID_Kupac;
    	    this.Oznaka = gridformated.Oznaka;
    	    this.Naziv = gridformated.Naziv;
    	    this.JMBG = gridformated.JMBG;
    	    this.Ulica = gridformated.Ulica;
    	    this.KucniBroj = gridformated.KucniBroj;
    	    this.KucniBrojDodatak = gridformated.KucniBrojDodatak;
    	    this.PostanskiBroj = gridformated.PostanskiBroj;
    	    this.OIB = gridformated.OIB;
    	    this.Posta = gridformated.Posta;
    	    this.ID_Posta = gridformated.ID_Posta;
    	    this.ID_Subjekt = gridformated.ID_Subjekt;
    	    this.ID_UgovorStanOtkupKupac = gridformated.ID_UgovorStanOtkupKupac;
    	    this.Nositelj = gridformated.Nositelj;
    	    this.ID_UgovorStanOtkup = gridformated.ID_UgovorStanOtkup;
    	}
    
    	/*
    	    mymodel.ID_Kupac = model.ID_Kupac;
    	    mymodel.Oznaka = model.Oznaka;
    	    mymodel.Naziv = model.Naziv;
    	    mymodel.JMBG = model.JMBG;
    	    mymodel.Ulica = model.Ulica;
    	    mymodel.KucniBroj = model.KucniBroj;
    	    mymodel.KucniBrojDodatak = model.KucniBrojDodatak;
    	    mymodel.PostanskiBroj = model.PostanskiBroj;
    	    mymodel.OIB = model.OIB;
    	    mymodel.Posta = model.Posta;
    	    mymodel.ID_Posta = model.ID_Posta;
    	    mymodel.ID_Subjekt = model.ID_Subjekt;
    	    mymodel.ID_UgovorStanOtkupKupac = model.ID_UgovorStanOtkupKupac;
    	    mymodel.Nositelj = model.Nositelj;
    	    mymodel.ID_UgovorStanOtkup = model.ID_UgovorStanOtkup;
    		
    	*/
    
    		#endregion
    }
}
