//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate.View
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjektFormFormattedBase
    {
    	#region Properities
    
        [Required(ErrorMessage = AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.ID_GlavnaKnjiga.Required)]
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.ID_GlavnaKnjiga.DisplayName)]
       	public long ID_GlavnaKnjiga { get; set; }
    
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.ID_KontniPlan.DisplayName)]
       	public Nullable<long> ID_KontniPlan { get; set; }
    
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.ID_PoslovnaGodina.DisplayName)]
       	public Nullable<long> ID_PoslovnaGodina { get; set; }
    
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.ID_PoslovniSubjekt.DisplayName)]
       	public Nullable<long> ID_PoslovniSubjekt { get; set; }
    
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.ID_Subjekt.DisplayName)]
       	public Nullable<long> ID_Subjekt { get; set; }
    
    	
        [StringLength(255, ErrorMessage = AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.Naziv.StringLength)]
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.Naziv.DisplayName)]
       	public string Naziv { get; set; }
    
    	
        [StringLength(50, ErrorMessage = AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.OIB.StringLength)]
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.OIB.DisplayName)]
       	public string OIB { get; set; }
    
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.Godina.DisplayName)]
       	public Nullable<int> Godina { get; set; }
    
    	
        [StringLength(3, ErrorMessage = AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.IDValuta.StringLength)]
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.IDValuta.DisplayName)]
       	public string IDValuta { get; set; }
    
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DatumFormat.ddMMyyyy, ApplyFormatInEditMode = true)]
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.DatumOd.DisplayName)]
       	public Nullable<System.DateTime> DatumOd { get; set; }
    
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DatumFormat.ddMMyyyy, ApplyFormatInEditMode = true)]
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.DatumDo.DisplayName)]
       	public Nullable<System.DateTime> DatumDo { get; set; }
    
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.AnalitikaOd.DisplayName)]
       	public Nullable<int> AnalitikaOd { get; set; }
    
    	
        [StringLength(20, ErrorMessage = AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.Oznaka.StringLength)]
    	[DisplayName(AtributClass.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt.Oznaka.DisplayName)]
       	public string Oznaka { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjektFormFormattedBase()
        { }
    	
    	public GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjektFormFormattedBase(Model.Data.View.GlavnaKnjigaKontniPlanPoslovnaGodinaPoslovniSubjekt formformated)
    	{
    	    this.ID_GlavnaKnjiga = formformated.ID_GlavnaKnjiga;
    	    this.ID_KontniPlan = formformated.ID_KontniPlan;
    	    this.ID_PoslovnaGodina = formformated.ID_PoslovnaGodina;
    	    this.ID_PoslovniSubjekt = formformated.ID_PoslovniSubjekt;
    	    this.ID_Subjekt = formformated.ID_Subjekt;
    	    this.Naziv = formformated.Naziv;
    	    this.OIB = formformated.OIB;
    	    this.Godina = formformated.Godina;
    	    this.IDValuta = formformated.IDValuta;
    	    this.DatumOd = formformated.DatumOd;
    	    this.DatumDo = formformated.DatumDo;
    	    this.AnalitikaOd = formformated.AnalitikaOd;
    	    this.Oznaka = formformated.Oznaka;
    	}
    
    	/*
    	    mymodel.ID_GlavnaKnjiga = model.ID_GlavnaKnjiga;
    	    mymodel.ID_KontniPlan = model.ID_KontniPlan;
    	    mymodel.ID_PoslovnaGodina = model.ID_PoslovnaGodina;
    	    mymodel.ID_PoslovniSubjekt = model.ID_PoslovniSubjekt;
    	    mymodel.ID_Subjekt = model.ID_Subjekt;
    	    mymodel.Naziv = model.Naziv;
    	    mymodel.OIB = model.OIB;
    	    mymodel.Godina = model.Godina;
    	    mymodel.IDValuta = model.IDValuta;
    	    mymodel.DatumOd = model.DatumOd;
    	    mymodel.DatumDo = model.DatumDo;
    	    mymodel.AnalitikaOd = model.AnalitikaOd;
    	    mymodel.Oznaka = model.Oznaka;
    		
    	*/
    
    		#endregion
    	
    }
}
