//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate.View
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.GridFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class TecajListaDetaljGridFormattedBase
    {
    	#region Properities
        [Required(ErrorMessage = AtributClass.TecajListaDetalj.ID_TecajLista.Required)]
    	[DisplayName(AtributClass.TecajListaDetalj.ID_TecajLista.DisplayName)]
        [ScaffoldColumn(false)]
      	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.TecajListaDetalj.ID_TecajLista.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.TecajListaDetalj.ID_TecajLista.Sortable)]
    	public long ID_TecajLista { get; set; }
    
        [Required(ErrorMessage = AtributClass.TecajListaDetalj.ID_Banka.Required)]
    	[DisplayName(AtributClass.TecajListaDetalj.ID_Banka.DisplayName)]
        [ScaffoldColumn(false)]
       	[JqGridColumnSearchable(false, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.TecajListaDetalj.ID_Banka.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.TecajListaDetalj.ID_Banka.Sortable)]
    	public long ID_Banka { get; set; }
    
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DatumFormat.ddMMyyyy, ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = AtributClass.TecajListaDetalj.Datum.Required)]
    	[DisplayName(AtributClass.TecajListaDetalj.Datum.DisplayName)]
       	 [JqGridColumnSearchable(false)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Center)]
    	[JqGridColumnFormatter(AtributClass.TecajListaDetalj.Datum.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.TecajListaDetalj.Datum.Sortable)]
    	public System.DateTime Datum { get; set; }
    
        [Required(ErrorMessage = AtributClass.TecajListaDetalj.RedniBroj.Required)]
    	[DisplayName(AtributClass.TecajListaDetalj.RedniBroj.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.TecajListaDetalj.RedniBroj.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.TecajListaDetalj.RedniBroj.Sortable)]
    	public int RedniBroj { get; set; }
    
    	[DisplayName(AtributClass.TecajListaDetalj.Godina.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.TecajListaDetalj.Godina.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.TecajListaDetalj.Godina.Sortable)]
    	public Nullable<int> Godina { get; set; }
    
    	[DisplayName(AtributClass.TecajListaDetalj.GodinaRedniBroj.DisplayName)]
       	[JqGridColumnSearchable(true, SearchType = JqGridColumnSearchTypes.Text, SearchOperators = JqGridSearchOperators.Eq)]
    	[JqGridColumnLayout(Alignment = JqGridAlignments.Right)]
    	[JqGridColumnFormatter(AtributClass.TecajListaDetalj.GodinaRedniBroj.Formatter)]
    	[JqGridColumnSortable(true, Index = AtributClass.TecajListaDetalj.GodinaRedniBroj.Sortable)]
    	public Nullable<int> GodinaRedniBroj { get; set; }
    
    	#endregion
    	
    	
    	#region Constructor
    	
    	public TecajListaDetaljGridFormattedBase()
        { }
    	
    	public TecajListaDetaljGridFormattedBase(Model.Data.View.TecajListaDetalj gridformated)
    	{
    	    this.ID_TecajLista = gridformated.ID_TecajLista;
    	    this.ID_Banka = gridformated.ID_Banka;
    	    this.Datum = gridformated.Datum;
    	    this.RedniBroj = gridformated.RedniBroj;
    	    this.Godina = gridformated.Godina;
    	    this.GodinaRedniBroj = gridformated.GodinaRedniBroj;
    	}
    
    	/*
    	    mymodel.ID_TecajLista = model.ID_TecajLista;
    	    mymodel.ID_Banka = model.ID_Banka;
    	    mymodel.Datum = model.Datum;
    	    mymodel.RedniBroj = model.RedniBroj;
    	    mymodel.Godina = model.Godina;
    	    mymodel.GodinaRedniBroj = model.GodinaRedniBroj;
    		
    	*/
    
    		#endregion
    }
}
