//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.GridFormattedTemplate.View.AtributClass
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    
    
    public static class UgovorStanOtkupObrokPreplata
    {
    	
    
    	public static class ID_UgovorStanOtkupObrokPreplata
    	{
    		public const string Item = "ID_UgovorStanOtkupObrokPreplata";
    	  public const string DisplayName = "ID_UgovorStanOtkupObrokPreplata"; 
    			public const string Required = "*";
     
      		public const string Formatter = "$.ID_UgovorStanOtkupObrokPreplataFormatter";
    		public const string Sortable = "ID_UgovorStanOtkupObrokPreplata";
    	}
    
    
    	public static class ID_UgovorStanOtkupObrok
    	{
    		public const string Item = "ID_UgovorStanOtkupObrok";
    	  public const string DisplayName = "ID_UgovorStanOtkupObrok"; 
    			public const string Formatter = "$.ID_UgovorStanOtkupObrokFormatter";
    		public const string Sortable = "ID_UgovorStanOtkupObrok";
    	}
    
    
    	public static class Datum
    	{
    		public const string Item = "Datum";
    	  public const string DisplayName = "Datum"; 
    			public const string Formatter = "$.DatumFormatter";
    		public const string Sortable = "Datum";
    	}
    
    
    	public static class IznosPreplata
    	{
    		public const string Item = "IznosPreplata";
    	  public const string DisplayName = "IznosPreplata"; 
    			public const string Formatter = "$.IznosPreplataFormatter";
    		public const string Sortable = "IznosPreplata";
    	}
    
    
    	public static class BrojUgovor
    	{
    		public const string Item = "BrojUgovor";
    	  public const string DisplayName = "BrojUgovor"; 
    			public const string Formatter = "$.BrojUgovorFormatter";
    		public const string Sortable = "BrojUgovor";
    	}
    
    
    	public static class Broj
    	{
    		public const string Item = "Broj";
    	  public const string DisplayName = "Broj"; 
    			public const string Formatter = "$.BrojFormatter";
    		public const string Sortable = "Broj";
    	}
    
    
    	public static class Aktivno
    	{
    		public const string Item = "Aktivno";
    	  public const string DisplayName = "Aktivno"; 
    			public const string Required = "*";
    		public const string Formatter = "$.AktivnoFormatter";
    		public const string Sortable = "Aktivno";
    	}
    
    
    	public static class ID_UgovorStanOtkup
    	{
    		public const string Item = "ID_UgovorStanOtkup";
    	  public const string DisplayName = "ID_UgovorStanOtkup"; 
    			public const string Formatter = "$.ID_UgovorStanOtkupFormatter";
    		public const string Sortable = "ID_UgovorStanOtkup";
    	}
    
    
    	public static class BrojObrok
    	{
    		public const string Item = "BrojObrok";
    	  public const string DisplayName = "BrojObrok"; 
    			public const string Formatter = "$.BrojObrokFormatter";
    		public const string Sortable = "BrojObrok";
    	}
    
    
    }
}
