//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class ZapisVrTablicaFormFormattedBase
    {
    	#region Properities
    
        [Required(ErrorMessage = AtributClass.ZapisVrTablica.IDZapisVr.Required)]
    	[DisplayName(AtributClass.ZapisVrTablica.IDZapisVr.DisplayName)]
       	public int IDZapisVr { get; set; }
    
        [Required(ErrorMessage = AtributClass.ZapisVrTablica.IDZapisTablica.Required)]
    	[DisplayName(AtributClass.ZapisVrTablica.IDZapisTablica.DisplayName)]
       	public int IDZapisTablica { get; set; }
    
    	[DisplayName(AtributClass.ZapisVrTablica.Odabir.DisplayName)]
       	public Nullable<bool> Odabir { get; set; }
    
        [Required(ErrorMessage = AtributClass.ZapisVrTablica.Analitika.Required)]
    	[DisplayName(AtributClass.ZapisVrTablica.Analitika.DisplayName)]
       	public bool Analitika { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public ZapisVrTablicaFormFormattedBase()
        { }
    	
    	public ZapisVrTablicaFormFormattedBase(Model.Data.ZapisVrTablica formformated)
    	{
    	    this.IDZapisVr = formformated.IDZapisVr;
    	    this.IDZapisTablica = formformated.IDZapisTablica;
    	    this.Odabir = formformated.Odabir;
    	    this.Analitika = formformated.Analitika;
    	}
    
    	/*
    	    mymodel.IDZapisVr = model.IDZapisVr;
    	    mymodel.IDZapisTablica = model.IDZapisTablica;
    	    mymodel.Odabir = model.Odabir;
    	    mymodel.Analitika = model.Analitika;
    		
    	*/
    
    		#endregion
    	
    }
}
