//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InLine.UI.Web.T4.FormFormattedTemplate
{
    
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Collections.Specialized;
    using System.Linq;
    using System.Web;
    using System.ComponentModel;
    using Lib.Web.Mvc.JQuery.JqGrid.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid;
    using System.ComponentModel.DataAnnotations;
    using Lib.Web.Mvc.JQuery.JqGrid.Constants;
    using System.Web.Mvc;
    using InLine;
    using InLine.UI.Web.T4.FormFormattedTemplate;
    using InLine.UI.Web.Helper;
    
    
    public partial class ZbrojniNalogFormFormattedBase
    {
    	#region Properities
    
        [Required(ErrorMessage = AtributClass.ZbrojniNalog.ID_ZbrojniNalog.Required)]
    	[DisplayName(AtributClass.ZbrojniNalog.ID_ZbrojniNalog.DisplayName)]
        	public long ID_ZbrojniNalog { get; set; }
    
        [Required(ErrorMessage = AtributClass.ZbrojniNalog.ID_Zapis.Required)]
    	[DisplayName(AtributClass.ZbrojniNalog.ID_Zapis.DisplayName)]
       	public long ID_Zapis { get; set; }
    
        [Required(ErrorMessage = AtributClass.ZbrojniNalog.IDZbrojniNalogVerzija.Required)]
    	[DisplayName(AtributClass.ZbrojniNalog.IDZbrojniNalogVerzija.DisplayName)]
       	public int IDZbrojniNalogVerzija { get; set; }
    
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DatumFormat.ddMMyyyy, ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = AtributClass.ZbrojniNalog.DatumPredaje.Required)]
    	[DisplayName(AtributClass.ZbrojniNalog.DatumPredaje.DisplayName)]
       	public System.DateTime DatumPredaje { get; set; }
    
    	[DataType(DataType.Date)]
    	[DisplayFormat(DataFormatString = KeyWord.FormaterRazno.DatumFormat.ddMMyyyy, ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = AtributClass.ZbrojniNalog.DatumValuta.Required)]
    	[DisplayName(AtributClass.ZbrojniNalog.DatumValuta.DisplayName)]
       	public System.DateTime DatumValuta { get; set; }
    
    	
        [StringLength(255, ErrorMessage = AtributClass.ZbrojniNalog.DatotekaNaziv.StringLength)]
    	[DisplayName(AtributClass.ZbrojniNalog.DatotekaNaziv.DisplayName)]
       	public string DatotekaNaziv { get; set; }
    
    	[DisplayName(AtributClass.ZbrojniNalog.Datoteka.DisplayName)]
       	public string Datoteka { get; set; }
    
    	#endregion
    
    	#region Constructor
    	
    	public ZbrojniNalogFormFormattedBase()
        { }
    	
    	public ZbrojniNalogFormFormattedBase(Model.Data.ZbrojniNalog formformated)
    	{
    	    this.ID_ZbrojniNalog = formformated.ID_ZbrojniNalog;
    	    this.ID_Zapis = formformated.ID_Zapis;
    	    this.IDZbrojniNalogVerzija = formformated.IDZbrojniNalogVerzija;
    	    this.DatumPredaje = formformated.DatumPredaje;
    	    this.DatumValuta = formformated.DatumValuta;
    	    this.DatotekaNaziv = formformated.DatotekaNaziv;
    	    this.Datoteka = formformated.Datoteka;
    	}
    
    	/*
    	    mymodel.ID_ZbrojniNalog = model.ID_ZbrojniNalog;
    	    mymodel.ID_Zapis = model.ID_Zapis;
    	    mymodel.IDZbrojniNalogVerzija = model.IDZbrojniNalogVerzija;
    	    mymodel.DatumPredaje = model.DatumPredaje;
    	    mymodel.DatumValuta = model.DatumValuta;
    	    mymodel.DatotekaNaziv = model.DatotekaNaziv;
    	    mymodel.Datoteka = model.Datoteka;
    		
    	*/
    
    		#endregion
    	
    }
}
